import { useEffect, useState } from 'react'
import { api, post } from './api'
import { useCommunity } from './context'
import { NotificationList } from './NotificationList'
import { notificationLines } from './notification-text'
import type { BellItem } from './notification-contract'
import { threadHref } from '../routing'
import { configurationSummary } from './configuration-report'
type Report={id:string;module_id:string;scope?:'module'|'configuration';module_count?:number;author_login:string;title:string;body:string;status:string;created_at:string;github_url:string|null;forum_thread_id:string|null}
export function AccountInbox(){
 const {session}=useCommunity(),[reports,setReports]=useState<Report[]|null>(null),[notifications,setNotifications]=useState<BellItem[]>([]),[error,setError]=useState('')
 useEffect(()=>{let cancelled=false;void Promise.all([api<Report[]>('/issues/mine'),session.user?.verified?api<{items:BellItem[]}>('/notifications').then(value=>value.items):Promise.resolve([])]).then(([reports,notifications])=>{if(!cancelled){setReports(reports);setNotifications(notifications)}}).catch(error=>{if(!cancelled)setError(error.message)});return()=>{cancelled=true}},[session.user?.id,session.user?.verified])
 async function markRead(ids?:string[]){try{await post('/notifications',ids?{ids}:{},'PATCH');setNotifications(items=>items.map(item=>!ids||ids.includes(item.id)?{...item,seen:true}:item))}catch(error){setError(error instanceof Error?error.message:'Unable to mark notifications read.')}}
 return <>
  {session.user?.verified&&<section className="configuration-section account-notifications" id="account-notifications"><div className="section-title"><h2>Notifications</h2><button className="text-button" disabled={!notifications.some(item=>!item.seen)} onClick={()=>void markRead()}>Mark all read</button></div>{notifications.length?<NotificationList lines={notificationLines(notifications)} onOpen={line=>{if(!line.seen)void markRead(line.ids)}}/>:<p className="service-note">Replies, mentions, likes, activity on modules you maintain, your bug report status and releases of modules you follow appear here and in the bell.</p>}<a href="#forum?saved=1">Your bookmarks →</a></section>}
  <section className="configuration-section"><h2>Your issue reports</h2>{error?<p className="file-error" role="alert">{error}</p>:reports===null?<p role="status">Loading reports…</p>:reports.length?reports.map(item=><article className="inbox-issue" key={item.id}><div className="section-title"><h3><a href={'#account/report/'+item.id}>{item.title}</a></h3><span className="pill">{item.status==='open'?'Open':'Resolved'}</span></div><small>{item.scope==='configuration'?'Whole configuration · '+configurationSummary(item.module_count??0):<>{item.module_id} · for @{item.author_login}</>}{item.github_url&&<> · <a href={item.github_url} target="_blank" rel="noreferrer">Public issue on GitHub ↗</a></>}</small>{item.forum_thread_id&&<a href={threadHref(item.forum_thread_id)}>Bug Reports discussion →</a>}<p className="preserve-lines">{item.body}</p></article>):<p className="service-note">No issue reports yet. Use “Report an issue” on a module page to send a bug to its developers.</p>}<p className="service-note">New bug descriptions are public on GitHub, where the module developers track them; their replies and fixes appear in your notifications. Reports from before GitHub tracking stay in the Bug Reports forum. Configuration details, logs and replies in your account stay private to you, the administrator and verified maintainers; you can stop sharing those private details. Earlier private reports stay private unless you choose to share them with maintainers. Older guest reports remain accessible only to the browser identity that created them. Accounts do not claim guest content by name.</p></section>
  </>
}
