import { BackLink } from '../components/BackLink'
import { RichTextEditor } from './ForumEditor'
import { useEffect, useState } from 'react'
import { api, apiFetch, post } from './api'
import { useCommunity } from './context'
import { type ForumPost, type SharedConfiguration, type ThreadDetail } from './forum-contract'
import { communityModule, nativeModule, moduleIssueHref } from './modules'
import { MemberPrompt } from './MemberPrompt'
import { Icon } from '../components/Icon'
import { ForumPostBody as PostContent } from './ForumPostBody'
import { ForumTime } from './ForumTime'
import { ForumAvatar as Avatar, ForumAuthorName as AuthorName, ForumCategoryBadge as CategoryBadge, ForumMachineBadge as MachineBadge } from './ForumIdentity'
import { DEVICES_BY_ID } from '../devices/registry'
import { ForumAttachments, MediaPicker } from './ForumMedia'
import { mediaBusy, readyAttachments, type PendingMedia } from './forum-media-client'
import { ModuleIssueNotice } from './ModuleIssueNotice'
import { ModuleDiscussionDialog } from './ModuleDiscussionDialog'
import { saveDiscussionIssueDraft } from './discussion-issue-draft'
function errorText(error:unknown){return error instanceof Error?error.message:'The request could not be completed.'}
function PostCard({item,author,locked,refresh,onQuote}:{item:ForumPost;author:string|null;locked:boolean;refresh:()=>Promise<void>;onQuote:(value:string)=>void}){
  const {session}=useCommunity(),[editing,setEditing]=useState(false),[body,setBody]=useState(item.body),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[reporting,setReporting]=useState(false)
  async function act(path:string,payload:unknown,method='POST'){setBusy(true);setError('');try{await post(path,payload,method);setEditing(false);await refresh();return true}catch(error){setError(errorText(error));return false}finally{setBusy(false)}}
  async function removeMedia(id:string){if(!window.confirm('Remove this file from your post? This cannot be undone.'))return;setBusy(true);setError('');try{const result=await apiFetch('/forum/media/'+id,{method:'DELETE'});if(!result.ok)throw new Error(((await result.json().catch(()=>({}))) as {error?:string}).error??'The file could not be removed.');await refresh()}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  return <article className="forum-post" data-author={!!item.official||!!item.username&&item.username===author} aria-label={(item.official?'Modwerk':item.username??item.displayName??'Deleted member')+'’s post'} id={'post-'+item.id}><header><Avatar username={item.username} official={item.official} avatar={item.avatar}/><div className="forum-post-author"><div>{item.official||item.username?<AuthorName username={item.username} official={item.official}/>:<strong>{item.hidden?'Removed post':item.displayName??'Deleted member'}</strong>}{item.username&&item.username===author&&<span className="forum-author-badge">Thread author</span>}{!!item.hidden&&<span className="pill">Hidden</span>}</div><div className="forum-meta"><ForumTime value={item.created_at}/>{item.edited_at&&<small>Edited</small>}</div></div></header>{item.hidden&&!session.admin?<p className="service-note">This post was removed.</p>:editing?<form className="community-form" onSubmit={event=>{event.preventDefault();void act('/forum/posts/'+item.id,{body},'PATCH')}}><div className="forum-editor-field"><label htmlFor={'forum-edit-'+item.id}>Edit your post</label><RichTextEditor id={'forum-edit-'+item.id} label="Edit your post" value={body} onChange={setBody} disabled={busy}/></div><div className="forum-actions"><button className="button button-primary" disabled={busy||!body.trim()||body.length>12000}>Save changes</button><button type="button" className="button button-quiet" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></div></form>:<PostContent body={item.body}/>}
    {(!item.hidden||session.admin)&&<ForumAttachments items={item.attachments??[]} privateFetch={!!item.hidden} onRemove={editing&&item.canRemoveMedia?attachment=>void removeMedia(attachment.id):undefined}/>}
    {!item.hidden&&<footer className="forum-post-actions">{session.user?.verified?<><button className="forum-post-action" disabled={busy} aria-label={`${item.liked?'Unlike':'Like'} this post (${item.likes} ${item.likes===1?'like':'likes'})`} aria-pressed={item.liked} onClick={()=>void act('/forum/posts/'+item.id+'/react',{liked:!item.liked})}><Icon name="heart" size={15}/> <span>{item.likes||'Like'}</span></button>{!locked&&<button className="forum-post-action" onClick={()=>onQuote('> '+(item.username?'@'+item.username:item.displayName??'Deleted member')+' wrote:\n'+item.body.split('\n').map(line=>'> '+line).join('\n')+'\n\n')}><Icon name="quote" size={15}/>Quote</button>}{item.canEdit&&<button className="forum-post-action" onClick={()=>{setBody(item.body);setEditing(true)}}>Edit</button>}<details open={reporting} onToggle={event=>setReporting(event.currentTarget.open)}><summary>Report post</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const reason=new FormData(event.currentTarget).get('reason');void act('/forum/posts/'+item.id+'/report',{reason}).then(ok=>{if(ok){setNotice('Report submitted to the administrator.');setReporting(false)}})}}><p className="service-note">Use this to report spam or rule violations. Reports go privately to the administrator.</p><label>Reason<textarea name="reason" required maxLength={1000} rows={2} placeholder="What should the administrator review?"/></label><div className="forum-actions"><button className="button button-quiet" disabled={busy}>Send report</button><button className="text-button" type="button" disabled={busy} onClick={()=>setReporting(false)}>Cancel</button></div></form></details></>:<span className="forum-readonly-likes"><Icon name="heart" size={15}/>{item.likes} {item.likes===1?'like':'likes'}</span>}</footer>}
    {session.admin&&<details><summary>Moderate post</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));const action=String(fields.action),file=action.startsWith('media:')?action.slice(6):'';void act('/admin/forum/'+(file?'media/'+file:action==='suspended'?'users/'+item.user_id:'posts/'+item.id),{action:file?'removed':action,value:action==='hidden'?!item.hidden:true,reason:fields.reason},'PATCH')}}><label>Action<select name="action"><option value="hidden">{item.hidden?'Restore post':'Hide post'}</option>{(item.attachments??[]).map((attachment,index)=><option key={attachment.id} value={'media:'+attachment.id}>Delete {attachment.kind==='image'?'image':'sound clip'} {index+1} permanently</option>)}{!item.official&&<option value="suspended">Suspend author</option>}</select></label><label>Reason<input name="reason" required maxLength={1000}/></label><button className="button button-quiet" disabled={busy}>Apply</button></form></details>}{notice&&<p role="status">{notice}</p>}{error&&<p className="file-error" role="alert">{error}</p>}</article>
}
export function ForumThreadView({id,query=new URLSearchParams(),onCopy,embedded=false,onReportIssue,onReplyCount}:{id:string;query?:URLSearchParams;onCopy?:(config:SharedConfiguration)=>void;embedded?:boolean;onReportIssue?:()=>void;onReplyCount?:(count:number)=>void}){
  const {session}=useCommunity(),[loaded,setLoaded]=useState<{key:string;data:ThreadDetail}|null>(null),[error,setError]=useState(''),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[media,setMedia]=useState<PendingMedia[]>([])
  const [localPage,setLocalPage]=useState(0),[revision,setRevision]=useState(0)
  const [confirming,setConfirming]=useState(false)
  const page=embedded?localPage:Number(query.get('page')??0),replyId='forum-reply-'+id
  const identity=id+':'+(session.user?.id??'')+':'+session.admin,key=identity+':'+page
  const data=loaded?.key===key?loaded.data:null
  async function load(nextPage=page){setLoaded({key:identity+':'+nextPage,data:await api<ThreadDetail>('/forum/threads/'+id+'?page='+nextPage)})}
  useEffect(()=>{let cancelled=false;void api<ThreadDetail>('/forum/threads/'+id+'?page='+page).then(value=>{if(!cancelled){setLoaded({key,data:value});setError('')}}).catch(error=>{if(!cancelled)setError(errorText(error))});return()=>{cancelled=true}},[id,page,key,revision])
  async function act(action:string,payload:unknown,method='POST'){setBusy(true);setError('');try{const result=await post<{id?:string;page?:number}>('/forum/threads/'+id+'/'+action,payload,method);const nextPage=action==='replies'?result.page??page:page;await load(nextPage);if(action==='replies'){setReply('');setMedia([]);setNotice('Reply posted.');if(embedded)setLocalPage(nextPage);else if(nextPage!==page)window.location.assign('#forum/thread/'+id+'?page='+nextPage+'&post='+result.id)}}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  // Links from the bell, the Showcase and Recent replies name a post; scroll to it once it is on this page.
  // The opening post is already in view under the title, so the page stays at the top for it.
  const target=query.get('post')
  useEffect(()=>{if(!data||!target||(page===0&&data.posts[0]?.id===target))return;document.getElementById('post-'+target)?.scrollIntoView({block:'start'})},[data,target,page])
  const replies=data?.thread.replies
  useEffect(()=>{if(replies!==undefined)onReplyCount?.(replies)},[replies,onReplyCount])
  const discussionModule=data?data.thread.category==='issues'?null:data.thread.module_id:embedded&&id.startsWith('module-')?id.slice(7):null
  const moduleDiscussion=!!discussionModule||data?.thread.category==='modules'
  function publishReply(){void act('replies',{body:reply,...(media.length?{attachments:readyAttachments(media)}:{})})}
  function requestReply(){if(moduleDiscussion)setConfirming(true);else publishReply()}
  function reportIssue(){
    if(!moduleDiscussion)return
    if(reply.trim())saveDiscussionIssueDraft(discussionModule??'',{title:'',body:reply})
    setConfirming(false)
    if(onReportIssue)onReportIssue();else window.location.assign(discussionModule?moduleIssueHref(discussionModule):'#forum/new?category=issues&draft=1'+(data?.thread.machine?'&machine='+encodeURIComponent(data.thread.machine):''))
  }
  const reportNotice=moduleDiscussion&&<ModuleIssueNotice moduleId={discussionModule} machine={data?.thread.machine??undefined} onReportIssue={reportIssue}/>
  if(!data)return <>{!embedded&&<BackLink href="#forum">All discussions</BackLink>}{reportNotice}{error?<><p className="file-error" role="alert">{error}</p><button className="button button-quiet" onClick={()=>setRevision(value=>value+1)}>Try again</button></>:<p role="status">Loading discussion…</p>}</>
  const {thread}=data
  return <>{embedded?<div className="section-title"><h2>Discussion <span className="subtle">{thread.replies}</span></h2><a className="text-button" href={"#forum/thread/"+id}>Open in forum <Icon name="arrow" size={14}/></a></div>:<BackLink href="#forum">All discussions</BackLink>}{!embedded&&<div className="page-heading forum-thread-heading"><div><div className="forum-thread-tags"><CategoryBadge category={thread.category}/><MachineBadge machine={thread.machine}/>{thread.module_id&&<a className="forum-module-link" href={communityModule(thread.module_id)?.href??'#forum'}>{communityModule(thread.module_id)?.name??thread.module_id}</a>}{!!thread.locked&&<span className="forum-state"><Icon name="lock" size={13}/>Locked</span>}{thread.category==='issues'&&<span className="forum-state" data-resolved={thread.status==='resolved'}>{thread.status==='resolved'?'Resolved':'Open'}</span>}</div><h1>{thread.title}</h1><div className="forum-meta"><Avatar username={thread.username} official={thread.official} avatar={thread.avatar}/><AuthorName username={thread.username} official={thread.official}/><span>Started <ForumTime value={thread.created_at} relative/></span><span>{thread.replies} {thread.replies===1?'reply':'replies'}</span></div></div></div>}
    {session.user?.verified&&<div className="forum-actions forum-thread-actions">{!thread.locked&&<button className="button button-primary" onClick={()=>document.getElementById(replyId)?.focus()}><Icon name="message" size={16}/>Reply</button>}<button className="button button-quiet" disabled={busy} aria-pressed={data.following} onClick={()=>void act('follow',{enabled:!data.following})}><Icon name={data.following?'check':'message'} size={15}/>{data.following?'Following':'Follow replies'}</button><button className="button button-quiet" disabled={busy} aria-pressed={data.bookmarked} onClick={()=>void act('bookmark',{enabled:!data.bookmarked})}><Icon name="bookmark" size={15}/>{data.bookmarked?'Bookmarked':'Bookmark'}</button>{thread.category==='issues'&&(thread.username===session.user.username||session.admin)&&<button className="button button-quiet" disabled={busy} onClick={()=>void act('status',{status:thread.status==='open'?'resolved':'open'},'PATCH')}><Icon name="check" size={15}/>{thread.status==='open'?'Mark resolved':'Reopen'}</button>}</div>}
    {data.configuration&&<aside className="forum-config"><h2>{data.configuration.name}</h2><ul>{data.configuration.moduleIds.map(module=><li key={module}>{nativeModule(data.configuration!.device??'octatrack',module)?.name??module} <span className="subtle">{data.configuration!.moduleVersions[module]}</span></li>)}</ul><p>{(data.configuration.device??'octatrack')==='octatrack'?<>Stock FX2 {data.configuration.keepStockFx2?'preserved':'compact'}. </>:<>{DEVICES_BY_ID[data.configuration.device!]?.name}. </>}Copy this snapshot to review compatibility and module availability before building.</p><button className="button button-primary" onClick={()=>{try{onCopy?.(data.configuration!)}catch(error){setError(errorText(error))}}}>Copy to my configurations</button></aside>}
    {data.issue&&<section className="forum-config"><h2>Reproduction details</h2><p>{data.issue.device} · {thread.module_id} · {data.issue.version}</p>{(['steps','expected','actual'] as const).filter(key=>data.issue![key]).map(key=><div key={key}><h3>{key==='steps'?'Steps to reproduce':key==='expected'?'Expected result':'What happened'}</h3><PostContent body={data.issue![key]}/></div>)}</section>}
    {session.admin&&<details className="forum-config"><summary>Moderate thread</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));setError('');void post('/admin/forum/threads/'+id,{action:fields.action,value:fields.value==='true',reason:fields.reason},'PATCH').then(()=>load()).catch(error=>setError(errorText(error)))}}><label>Action<select name="action"><option value="locked">Lock</option><option value="pinned">Pin</option><option value="hidden">Hide</option></select></label><label>Set to<select name="value"><option value="true">On</option><option value="false">Off</option></select></label><label>Reason<input name="reason" required maxLength={1000}/></label><button className="button button-quiet">Apply</button></form></details>}
    <div className="forum-posts">{data.posts.map(item=><PostCard key={item.id} item={item} author={thread.username} locked={!!thread.locked} refresh={()=>load()} onQuote={value=>{setReply(current=>current+value);document.getElementById(replyId)?.focus()}}/>)}</div>{(page>0||data.hasMore)&&<nav className="forum-pagination" aria-label="Reply pages">{page>0?embedded?<button className="button button-quiet" onClick={()=>setLocalPage(page-1)}><Icon name="back" size={14}/>Previous replies</button>:<a className="button button-quiet" href={'#forum/thread/'+id+'?page='+(page-1)}><Icon name="back" size={14}/>Previous replies</a>:<span/>}<span>Page {page+1}</span>{data.hasMore&&(embedded?<button className="button button-quiet" onClick={()=>setLocalPage(page+1)}>More replies<Icon name="arrow" size={14}/></button>:<a className="button button-quiet" href={'#forum/thread/'+id+'?page='+(page+1)}>More replies<Icon name="arrow" size={14}/></a>)}</nav>}
    {reportNotice}
    <MemberPrompt/>{thread.locked?<p className="forum-locked-note"><Icon name="lock" size={16}/>This thread is locked. You can still read and bookmark it.</p>:session.user?.verified&&<form className="community-form forum-composer forum-reply-composer" onSubmit={event=>{event.preventDefault();requestReply()}}><div className="forum-composer-heading"><Avatar username={session.user.username} avatar={session.user.avatar}/><div><label htmlFor={replyId}>Your reply</label><p>Replying as @{session.user.username}</p></div></div><RichTextEditor id={replyId} label="Your reply" value={reply} onChange={setReply} disabled={busy} placeholder="Add your experience, an idea, or a question…"/>{session.forumMedia&&<MediaPicker items={media} setItems={setMedia}/>}<div className="forum-composer-footer"><span id="forum-reply-hint">Use the toolbar to format your reply. Shift + Enter adds a line break.</span><button className="button button-primary" disabled={busy||mediaBusy(media)||!reply.trim()||reply.length>12000}>{busy?'Posting…':'Post reply'}<Icon name="arrow" size={15}/></button></div></form>}{confirming&&<ModuleDiscussionDialog onClose={()=>setConfirming(false)} onPost={()=>{setConfirming(false);publishReply()}} onReportIssue={reportIssue}/>} {notice&&<p className="success-note" role="status">{notice}</p>}{error&&<p className="file-error" role="alert">{error}</p>}</>
}
