import { BackLink } from '../components/BackLink'
import { RichTextEditor } from './ForumEditor'
import { useEffect, useRef, useState, type ReactNode } from 'react'
import { api, apiFetch, post } from './api'
import { useCommunity } from './context'
import { REQUEST_STATUSES, type ForumPost, type SharedConfiguration, type ThreadDetail } from './forum-contract'
import { accountHref } from './member-access'
import { communityModule, nativeModule, moduleIssueHref, modulePageHref } from './modules'
import { MemberPrompt } from './MemberPrompt'
import { useLoginPrompt } from './LoginPromptDialog'
import { ShareModuleButton } from './ShareModuleButton'
import { Icon } from '../components/Icon'
import { ForumPostBody as PostContent } from './ForumPostBody'
import { ForumTime } from './ForumTime'
import { ForumAvatar as Avatar, ForumAuthorName as AuthorName, ForumCategoryBadge as CategoryBadge, ForumMachineBadge as MachineBadge, ForumMaintainerBadge as MaintainerBadge, ForumRoleBadge as RoleBadge } from './ForumIdentity'
import { DEVICES_BY_ID } from '../devices/registry'
import { ForumAttachments, MediaPicker } from './ForumMedia'
import { mediaBusy, readyAttachments, type PendingMedia } from './forum-media-client'
import { ModuleIssueNotice } from './ModuleIssueNotice'
import { ModuleDiscussionDialog } from './ModuleDiscussionDialog'
import { saveDiscussionIssueDraft } from './discussion-issue-draft'
import { useForumReplyDraft } from './forum-reply-draft'
import { threadHref } from '../routing'
import { setPageMetadata } from '../page-metadata'
import { postExcerpt } from './forum-links'
import { ReplyStarters } from './ReplyStarters'
import { ModuleWorksCount } from './ModuleWorksCount'
import { MODULE_STATISTICS_CHANGED } from './module-statistics'
import { starterBody, type ReplyStarter } from './reply-starters'
import { RenderBoundary } from '../components/RenderBoundary'
function errorText(error:unknown){return error instanceof Error?error.message:'The request could not be completed.'}
function PostCard({item,author,locked,opening,refresh,onQuote,onVisitor}:{item:ForumPost;author:string|null;locked:boolean;opening:boolean;refresh:()=>Promise<void>;onQuote:(value:string)=>void;onVisitor:(action:string)=>void}){
  const {session}=useCommunity(),[editing,setEditing]=useState(false),[body,setBody]=useState(item.body),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[reporting,setReporting]=useState(false)
  async function act(path:string,payload:unknown,method='POST'){setBusy(true);setError('');try{await post(path,payload,method);setEditing(false);await refresh();if(method==='PATCH')window.dispatchEvent(new Event(MODULE_STATISTICS_CHANGED));return true}catch(error){setError(errorText(error));return false}finally{setBusy(false)}}
  // The first post is the thread itself, so only replies can be deleted.
  async function remove(){if(window.confirm('Delete this post? This cannot be undone.')){await act('/forum/posts/'+item.id,{},'DELETE');window.dispatchEvent(new Event(MODULE_STATISTICS_CHANGED))}}
  async function removeMedia(id:string){if(!window.confirm('Remove this file from your post? This cannot be undone.'))return;setBusy(true);setError('');try{const result=await apiFetch('/forum/media/'+id,{method:'DELETE'});if(!result.ok)throw new Error(((await result.json().catch(()=>({}))) as {error?:string}).error??'The file could not be removed.');await refresh()}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  return <article className="forum-post" data-author={!!item.official||!!item.username&&item.username===author} aria-label={(item.official?'Modwerk':item.username??item.displayName??'Deleted member')+'’s post'} id={'post-'+item.id}><header><Avatar username={item.username} official={item.official} avatar={item.avatar}/><div className="forum-post-author"><div>{item.official||item.username?<><AuthorName username={item.username} official={item.official}/><RoleBadge role={item.role} betaTester={item.betaTester}/></>:<strong>{item.hidden?'Removed post':item.displayName??'Deleted member'}</strong>}{item.username&&item.username===author&&<span className="forum-author-badge">Thread author</span>}{item.maintainer&&<MaintainerBadge/>}{!!item.hidden&&<span className="pill">Hidden</span>}</div><div className="forum-meta"><ForumTime value={item.created_at}/>{item.edited_at&&<small>Edited</small>}</div></div></header>{item.hidden&&!session.admin?<p className="service-note">This post was removed.</p>:editing?<form className="community-form" onSubmit={event=>{event.preventDefault();void act('/forum/posts/'+item.id,{body},'PATCH')}}><div className="forum-editor-field"><label htmlFor={'forum-edit-'+item.id}>Edit your post</label><RichTextEditor id={'forum-edit-'+item.id} label="Edit your post" value={body} onChange={setBody} disabled={busy}/></div><div className="forum-actions"><button className="button button-primary" disabled={busy||!body.trim()||body.length>12000}>Save changes</button><button type="button" className="button button-quiet" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></div></form>:<PostContent body={item.body}/>}
    {(!item.hidden||session.admin)&&<ForumAttachments items={item.attachments??[]} privateFetch={!!item.hidden} onRemove={editing&&item.canRemoveMedia?attachment=>void removeMedia(attachment.id):undefined}/>}
    {!item.hidden&&<footer className="forum-post-actions">{session.user?.verified?<><button className="forum-post-action" disabled={busy} aria-label={`${item.liked?'Unlike':'Like'} this post (${item.likes} ${item.likes===1?'like':'likes'})`} aria-pressed={item.liked} onClick={()=>void act('/forum/posts/'+item.id+'/react',{liked:!item.liked})}><Icon name="heart" size={15}/> <span>{item.likes||'Like'}</span></button>{!locked&&<button className="forum-post-action" onClick={()=>onQuote('> '+(item.username?'@'+item.username:item.displayName??'Deleted member')+' wrote:\n'+item.body.split('\n').map(line=>'> '+line).join('\n')+'\n\n')}><Icon name="quote" size={15}/>Quote</button>}{item.canEdit&&<button className="forum-post-action" onClick={()=>{setBody(item.body);setEditing(true)}}>Edit</button>}{item.canEdit&&!opening&&<button className="forum-post-action" disabled={busy} onClick={()=>void remove()}>Delete</button>}<details open={reporting} onToggle={event=>setReporting(event.currentTarget.open)}><summary>Report post</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const reason=new FormData(event.currentTarget).get('reason');void act('/forum/posts/'+item.id+'/report',{reason}).then(ok=>{if(ok){setNotice('Report submitted to the administrator.');setReporting(false)}})}}><p className="service-note">Use this to report spam or rule violations. Reports go privately to the administrator.</p><label>Reason<textarea name="reason" required maxLength={1000} rows={2} placeholder="What should the administrator review?"/></label><div className="forum-actions"><button className="button button-quiet" disabled={busy}>Send report</button><button className="text-button" type="button" disabled={busy} onClick={()=>setReporting(false)}>Cancel</button></div></form></details></>:session.user?<span className="forum-readonly-likes"><Icon name="heart" size={15}/>{item.likes} {item.likes===1?'like':'likes'}</span>:<button className="forum-post-action" aria-haspopup="dialog" aria-label={`Like this post (${item.likes} ${item.likes===1?'like':'likes'})`} onClick={()=>onVisitor('Sign in to like this post')}><Icon name="heart" size={15}/> <span>{item.likes||'Like'}</span></button>}</footer>}
    {session.admin&&<details><summary>Moderate post</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));const action=String(fields.action),file=action.startsWith('media:')?action.slice(6):'';if(action==='deleted'&&!window.confirm('Delete this post permanently? This cannot be undone.'))return;void act('/admin/forum/'+(file?'media/'+file:action==='suspended'?'users/'+item.user_id:'posts/'+item.id),{action:file?'removed':action,value:action==='hidden'?!item.hidden:true,reason:fields.reason},'PATCH')}}><label>Action<select name="action"><option value="hidden">{item.hidden?'Restore post':'Hide post'}</option>{(item.attachments??[]).map((attachment,index)=><option key={attachment.id} value={'media:'+attachment.id}>Delete {attachment.kind==='image'?'image':'sound clip'} {index+1} permanently</option>)}{!opening&&<option value="deleted">Delete post permanently</option>}{!item.official&&<option value="suspended">Suspend author</option>}</select></label><label>Reason<input name="reason" required maxLength={1000}/></label><button className="button button-quiet" disabled={busy}>Apply</button></form></details>}{notice&&<p role="status">{notice}</p>}{error&&<p className="file-error" role="alert">{error}</p>}</article>
}
/** Shares the thread's public path: the system share sheet where there is one, otherwise the clipboard. */
function ShareButton({title,href}:{title:string;href:string}){
  const [state,setState]=useState<''|'copied'|'failed'>('')
  useEffect(()=>{if(!state)return;const timer=window.setTimeout(()=>setState(''),2500);return()=>window.clearTimeout(timer)},[state])
  async function share(){
    const url=new URL(href,document.baseURI).href
    try{
      if(typeof navigator.share==='function'){await navigator.share({title,url});return}
      await navigator.clipboard.writeText(url);setState('copied')
    }catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;setState('failed')}
  }
  return <button type="button" className="forum-share" onClick={()=>void share()} aria-label="Share this discussion"><Icon name="share" size={14}/><span aria-live="polite">{state==='copied'?'Link copied':state==='failed'?'Copy the address bar':'Share'}</span></button>
}
// The automatic opening post of a module's home thread is boilerplate; keep it to one line so the replies come first.
function ModuleIntro({initiallyOpen,children}:{initiallyOpen:boolean;children:ReactNode}){
  const [open,setOpen]=useState(initiallyOpen)
  return <details className="forum-intro" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary><strong>Modwerk</strong><span>About this discussion</span><Icon name="arrow" size={13}/></summary>{children}</details>
}
type ThreadViewProps={id:string;query?:URLSearchParams;onCopy?:(config:SharedConfiguration)=>void;embedded?:boolean;onReportIssue?:()=>void;onReplyCount?:(count:number)=>void}
export function ForumThreadView(props:ThreadViewProps){
  const fallback=<>{!props.embedded&&<BackLink href="#forum">All discussions</BackLink>}<div role="alert"><h2>Discussion could not open</h2><p className="service-note">Reload the page to try again. Your saved reply draft stays in this tab.</p><button type="button" className="button button-quiet" onClick={()=>window.location.reload()}>Reload discussion</button></div></>
  return <RenderBoundary key={props.id+'?'+(props.query?.toString()??'')} fallback={fallback}><ForumThreadContent {...props}/></RenderBoundary>
}
function ForumThreadContent({id,query=new URLSearchParams(),onCopy,embedded=false,onReportIssue,onReplyCount}:ThreadViewProps){
  const {session}=useCommunity(),[loaded,setLoaded]=useState<{key:string;data:ThreadDetail}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[media,setMedia]=useState<PendingMedia[]>([])
  const [reply,setReply]=useForumReplyDraft(id,session.user?.id??'')
  const [localPage,setLocalPage]=useState(0),[revision,setRevision]=useState(0)
  const [confirming,setConfirming]=useState(false),[starter,setStarter]=useState<ReplyStarter|''>('')
  // Where the member's reading left off, kept from the first load of this visit: later loads have already moved the marker.
  const [unreadStart,setUnreadStart]=useState<{id:string;page:number}|null>(null),pendingJump=useRef('')
  const page=embedded?localPage:Number(query.get('page')??0),replyId='forum-reply-'+id
  // A visitor's sign-in returns to this thread (or the module page that embeds it); `?reply=1` then focuses the reply box.
  const threadRoute='forum/thread/'+id,{dialog,prompt}=useLoginPrompt(embedded&&id.startsWith('module-')?modulePageHref(id.slice(7)).slice(1):threadRoute)
  const replyPrompt=()=>prompt('Sign in to reply',embedded?undefined:threadRoute+'?reply=1')
  const focusedReply=useRef(false)
  const identity=id+':'+(session.user?.id??'')+':'+session.admin,key=identity+':'+page
  const data=loaded?.key===key?loaded.data:null
  useEffect(() => {
    if (embedded || !data) return
    setPageMetadata({ title: data.thread.title + ' — Modwerk forum', description: page === 0 ? postExcerpt(data.posts[0]?.body ?? '') : 'Discussion on the Modwerk forum.', url: new URL(threadHref(id, data.thread.title), document.baseURI).href })
  }, [embedded, data, id, page])
  async function load(nextPage=page){setLoaded({key:identity+':'+nextPage,data:await api<ThreadDetail>('/forum/threads/'+id+'?page='+nextPage)})}
  useEffect(()=>{let cancelled=false;void api<ThreadDetail>('/forum/threads/'+id+'?page='+page).then(value=>{if(!cancelled){setLoaded({key,data:value});setError('');if(value.firstUnread)setUnreadStart(current=>current??value.firstUnread??null)}}).catch(error=>{if(!cancelled)setError(errorText(error))});return()=>{cancelled=true}},[id,page,key,revision])
  async function act(action:string,payload:unknown,method='POST'){setBusy(true);setError('');try{const result=await post<{id?:string;page?:number}>('/forum/threads/'+id+'/'+action,payload,method);const nextPage=action==='replies'?result.page??page:page;await load(nextPage);if(action==='replies'){window.dispatchEvent(new Event(MODULE_STATISTICS_CHANGED));setReply('');setStarter('');setMedia([]);setNotice('Reply posted.');if(embedded)setLocalPage(nextPage);else if(nextPage!==page)window.location.assign('#forum/thread/'+id+'?page='+nextPage+'&post='+result.id)}}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  // Links from the bell, the Showcase and Recent replies name a post; scroll to it once it is on this page.
  // The opening post is already in view under the title, so the page stays at the top for it.
  const target=query.get('post')
  useEffect(()=>{if(!data||!target||(page===0&&data.posts[0]?.id===target))return;document.getElementById('post-'+target)?.scrollIntoView({block:'start'})},[data,target,page])
  // An embedded view turns its own pages, so the jump waits for the page that holds the reply.
  useEffect(()=>{if(!data||!pendingJump.current)return;const target=document.getElementById('post-'+pendingJump.current);if(target){pendingJump.current='';target.scrollIntoView({block:'start'})}},[data])
  function jumpToUnread(){
    if(!unreadStart)return
    setUnreadStart(null)
    if(unreadStart.page===page){document.getElementById('post-'+unreadStart.id)?.scrollIntoView({block:'start'});return}
    if(!embedded){window.location.assign('#forum/thread/'+id+'?page='+unreadStart.page+'&post='+unreadStart.id);return}
    pendingJump.current=unreadStart.id;setLocalPage(unreadStart.page)
  }
  const replies=data?.thread.replies
  const wantsReply=query.get('reply')==='1'&&!!session.user?.verified
  useEffect(()=>{if(data&&wantsReply&&!data.thread.locked&&!focusedReply.current){focusedReply.current=true;document.getElementById(replyId)?.focus()}},[data,wantsReply,replyId])
  useEffect(()=>{if(replies!==undefined)onReplyCount?.(replies)},[replies,onReplyCount])
  const discussionModule=data?data.thread.category==='issues'?null:data.thread.module_id:embedded&&id.startsWith('module-')?id.slice(7):null
  const moduleDiscussion=!!discussionModule||data?.thread.category==='modules'
  const machineName=data?.thread.machine?DEVICES_BY_ID[data.thread.machine]?.name??'':''
  function publishReply(){void act('replies',{body:moduleDiscussion?starterBody(starter,machineName,reply):reply,...(media.length?{attachments:readyAttachments(media)}:{})})}
  // A report that the module works is no bug report, so it skips the dialog that points bugs to the issue form.
  function requestReply(){if(moduleDiscussion&&starter!=='works')setConfirming(true);else publishReply()}
  function reportIssue(){
    if(!moduleDiscussion)return
    if(reply.trim())saveDiscussionIssueDraft(discussionModule??'',{title:'',body:reply})
    setConfirming(false)
    if(onReportIssue)onReportIssue();else window.location.assign(discussionModule?moduleIssueHref(discussionModule):'#forum/new?category=issues&draft=1'+(data?.thread.machine?'&machine='+encodeURIComponent(data.thread.machine):''))
  }
  const reportNotice=moduleDiscussion&&<ModuleIssueNotice moduleId={discussionModule} machine={data?.thread.machine??undefined} onReportIssue={reportIssue}/>
  if(!data)return <>{!embedded&&<BackLink href="#forum">All discussions</BackLink>}{reportNotice}{error?<><p className="file-error" role="alert">{error}</p><button className="button button-quiet" onClick={()=>setRevision(value=>value+1)}>Try again</button></>:<p role="status">Loading discussion…</p>}</>
  const {thread}=data
  return <>{embedded?<div className="section-title"><h2>Discussion <span className="subtle">{thread.replies}</span> {discussionModule && <ModuleWorksCount count={thread.worksReports}/>}</h2><a className="text-button" href={threadHref(id,thread.title)}>Open in forum <Icon name="arrow" size={14}/></a></div>:<BackLink href="#forum">All discussions</BackLink>}{!embedded&&<div className="page-heading forum-thread-heading"><div><div className="forum-thread-tags"><CategoryBadge category={thread.category}/><MachineBadge machine={thread.machine}/>{moduleDiscussion && <ModuleWorksCount count={thread.worksReports}/>} {thread.module_id&&<a className="forum-module-link" href={communityModule(thread.module_id)?.href??'#forum'}>{communityModule(thread.module_id)?.name??thread.module_id}</a>}{!!thread.locked&&<span className="forum-state"><Icon name="lock" size={13}/>Locked</span>}{thread.category==='issues'&&<span className="forum-state" data-resolved={thread.status==='resolved'}>{thread.status==='resolved'?'Resolved':'Open'}</span>}{thread.category==='requests'&&<span className="forum-state" data-request-status={thread.request_status}>{thread.request_status==='shipped'&&<Icon name="check" size={13}/>}{REQUEST_STATUSES[thread.request_status]}</span>}</div><h1>{thread.title}</h1><div className="forum-meta"><Avatar username={thread.username} official={thread.official} avatar={thread.avatar}/><AuthorName username={thread.username} official={thread.official}/><span>Started <ForumTime value={thread.created_at} relative/></span><span>{thread.replies} {thread.replies===1?'reply':'replies'}</span><ShareButton title={thread.title} href={threadHref(id,thread.title)}/></div></div>
    {thread.category==='requests'&&<div className="forum-vote">{session.user?.verified?<button className="button button-primary" disabled={busy} aria-pressed={data.voted} aria-label={`${data.voted?'Withdraw your vote':'Vote for this request'} (${thread.votes} ${thread.votes===1?'vote':'votes'})`} onClick={()=>void act('vote',{enabled:!data.voted})}><Icon name="heart" size={16}/>{data.voted?'Voted':'Vote'}<strong>{thread.votes}</strong></button>:<a className="button button-primary" href={session.user?'#account':accountHref('login','forum/thread/'+id)}><Icon name="heart" size={16}/>Vote<strong>{thread.votes}</strong></a>}<small>{thread.votes} {thread.votes===1?'vote':'votes'}{session.user?.verified?'':session.user?' · Verify your email to vote':' · Sign in to vote'}</small></div>}{!!thread.official&&thread.module_id&&<ShareModuleButton id={thread.module_id} title={communityModule(thread.module_id)?.name??thread.title}/>}</div>}
    {session.user?.verified&&<div className="forum-actions forum-thread-actions">{!thread.locked&&<button className="button button-primary" onClick={()=>document.getElementById(replyId)?.focus()}><Icon name="message" size={16}/>Reply</button>}<button className="button button-quiet" disabled={busy} aria-pressed={data.following} onClick={()=>void act('follow',{enabled:!data.following})}><Icon name={data.following?'check':'message'} size={15}/>{data.following?'Following':'Follow replies'}</button><button className="button button-quiet" disabled={busy} aria-pressed={data.bookmarked} onClick={()=>void act('bookmark',{enabled:!data.bookmarked})}><Icon name="bookmark" size={15}/>{data.bookmarked?'Bookmarked':'Bookmark'}</button>{thread.category==='issues'&&(thread.username===session.user.username||session.admin)&&<button className="button button-quiet" disabled={busy} onClick={()=>void act('status',{status:thread.status==='open'?'resolved':'open'},'PATCH')}><Icon name="check" size={15}/>{thread.status==='open'?'Mark resolved':'Reopen'}</button>}
    {thread.category==='requests'&&data.canSetRequestStatus&&<form key={thread.request_status} className="forum-request-status" aria-label="Request status" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void act('request-status',{status:fields.get('status'),note:fields.get('note')},'PATCH')}}><label><span className="sr-only">Status</span><select name="status" defaultValue={thread.request_status}>{Object.entries(REQUEST_STATUSES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span className="sr-only">Private note</span><input name="note" maxLength={1000} placeholder="Note for the history (optional)"/></label><button className="button button-quiet" disabled={busy}>Set status</button></form>}</div>}
    {!session.user&&<div className="forum-actions forum-thread-actions">{!thread.locked&&<button className="button button-primary" aria-haspopup="dialog" onClick={replyPrompt}><Icon name="message" size={16}/>Reply</button>}<button className="button button-quiet" aria-haspopup="dialog" onClick={()=>prompt('Sign in to follow replies')}><Icon name="message" size={15}/>Follow replies</button><button className="button button-quiet" aria-haspopup="dialog" onClick={()=>prompt('Sign in to bookmark this thread')}><Icon name="bookmark" size={15}/>Bookmark</button></div>}
    {data.configuration&&<aside className="forum-config"><h2>{data.configuration.name}</h2><ul>{data.configuration.moduleIds.map(module=><li key={module}>{nativeModule(data.configuration!.device??'octatrack',module)?.name??module} <span className="subtle">{data.configuration!.moduleVersions[module]}</span></li>)}</ul><p>{(data.configuration.device??'octatrack')==='octatrack'?<>Stock FX2 {data.configuration.keepStockFx2?'preserved':'compact'}. </>:<>{DEVICES_BY_ID[data.configuration.device!]?.name}. </>}Copy this snapshot to review compatibility and module availability before building.</p><button className="button button-primary" onClick={()=>{try{onCopy?.(data.configuration!)}catch(error){setError(errorText(error))}}}>Copy to my configurations</button></aside>}
    {data.issue&&<section className="forum-config"><h2>Reproduction details</h2><p>{data.issue.device} · {thread.module_id} · {data.issue.version}</p>{(['steps','expected','actual'] as const).filter(key=>data.issue![key]).map(key=><div key={key}><h3>{key==='steps'?'Steps to reproduce':key==='expected'?'Expected result':'What happened'}</h3><PostContent body={data.issue![key]}/></div>)}</section>}
    {session.admin&&<details className="forum-config"><summary>Moderate thread</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));setError('');void post('/admin/forum/threads/'+id,{action:fields.action,value:fields.value==='true',reason:fields.reason},'PATCH').then(()=>load()).catch(error=>setError(errorText(error)))}}><label>Action<select name="action"><option value="locked">Lock</option><option value="pinned">Pin</option><option value="hidden">Hide</option></select></label><label>Set to<select name="value"><option value="true">On</option><option value="false">Off</option></select></label><label>Reason<input name="reason" required maxLength={1000}/></label><button className="button button-quiet">Apply</button></form></details>}
    {unreadStart&&<p className="forum-unread-jump"><button type="button" className="text-button" onClick={jumpToUnread}><Icon name="arrow" size={13}/>Jump to first unread reply</button></p>}
    <div className="forum-posts">{data.posts.map((item,index)=>{const card=<PostCard key={item.id} item={item} author={thread.username} locked={!!thread.locked} opening={page===0&&index===0} refresh={()=>load()} onQuote={value=>{setReply(current=>current+value);document.getElementById(replyId)?.focus()}} onVisitor={prompt}/>;return moduleDiscussion&&page===0&&index===0&&item.official?<ModuleIntro key={item.id} initiallyOpen={target===item.id}>{card}</ModuleIntro>:card})}</div>{(page>0||data.hasMore)&&<nav className="forum-pagination" aria-label="Reply pages">{page>0?embedded?<button className="button button-quiet" onClick={()=>setLocalPage(page-1)}><Icon name="back" size={14}/>Previous replies</button>:<a className="button button-quiet" href={threadHref(id,thread.title,'?page='+(page-1))}><Icon name="back" size={14}/>Previous replies</a>:<span/>}<span>Page {page+1}</span>{data.hasMore&&(embedded?<button className="button button-quiet" onClick={()=>setLocalPage(page+1)}>More replies<Icon name="arrow" size={14}/></button>:<a className="button button-quiet" href={threadHref(id,thread.title,'?page='+(page+1))}>More replies<Icon name="arrow" size={14}/></a>)}</nav>}
    {reportNotice}
    <MemberPrompt/>{thread.locked?<p className="forum-locked-note"><Icon name="lock" size={16}/>This thread is locked. You can still read and bookmark it.</p>:session.user?.verified?<form className="community-form forum-composer forum-reply-composer" onSubmit={event=>{event.preventDefault();requestReply()}}><div className="forum-composer-heading"><Avatar username={session.user.username} avatar={session.user.avatar}/><div><label htmlFor={replyId}>Your reply</label><p>Replying as @{session.user.username}</p></div></div>{moduleDiscussion&&machineName&&<ReplyStarters machine={thread.machine!} machineName={machineName} moduleId={discussionModule} value={starter} onChange={setStarter} disabled={busy}/>}<RichTextEditor id={replyId} label="Your reply" value={reply} onChange={setReply} disabled={busy} placeholder="Add your experience, an idea, or a question…"/>{session.forumMedia&&<MediaPicker items={media} setItems={setMedia}/>}<div className="forum-composer-footer"><span id="forum-reply-hint">Use the toolbar to format your reply. Shift + Enter adds a line break.</span><button className="button button-primary" disabled={busy||mediaBusy(media)||!reply.trim()||reply.length>12000}>{busy?'Posting…':'Post reply'}<Icon name="arrow" size={15}/></button></div></form>:!session.user&&<form className="community-form forum-composer forum-reply-composer" aria-label="Reply as a member" onSubmit={event=>{event.preventDefault();replyPrompt()}}><div className="forum-editor-field"><label htmlFor={replyId}>Your reply</label><textarea id={replyId} rows={3} readOnly placeholder="Add your experience, an idea, or a question…" aria-haspopup="dialog" onClick={replyPrompt} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();replyPrompt()}}}/></div><div className="forum-composer-footer"><span>Replying takes a free Modwerk account.</span><button className="button button-primary">Post reply<Icon name="arrow" size={15}/></button></div></form>}{dialog}{confirming&&<ModuleDiscussionDialog onClose={()=>setConfirming(false)} onPost={()=>{setConfirming(false);publishReply()}} onReportIssue={reportIssue}/>} {notice&&<p className="success-note" role="status">{notice}</p>}{error&&<p className="file-error" role="alert">{error}</p>}</>
}
