# SPDX-License-Identifier: GPL-3.0-or-later
"""The private base's own USB configuration: stock mass storage plus Modwerk's
endpoint-free vendor interface, and the EP0 glue that answers IDENTIFY.

Elekloader cannot share a stock site between packages, and a descriptor change
needs a base install anyway, so the base owns the configuration responder and
the unknown-request tail. USB MIDI and USB Audio are not combined with this
yet: they claim the same sites. The mass-storage interface is byte for byte
the one USB MIDI's hardware-proven configurations carry (descriptors.py).

Developer source recipe only; no stock bytes, firmware or device access.
"""
import hashlib
import struct

VENDOR_CLASS, VENDOR_SUBCLASS, VENDOR_PROTOCOL = 0xff, 0x4d, 1
MSC_INTERFACE, VENDOR_INTERFACE = 0, 1
MODEL = 'OCTATRACK 1.40C'

# OS 1.40C. The responder's four `pea <configuration>` operands (stock: the
# protected tables at 0x400e201c..), the two `moveq #32` clamps it applies to
# GET_DESCRIPTOR(CONFIG / OTHER_SPEED) (12 bytes each: d1 = min(wLength, 32),
# rejoining after them), and the unknown-request STALL tail where every
# vendor request arrives (`movel ENDPTCTRL0,%d0`, rejoining at +6). Each
# detour replaces only its first 6 bytes, as USB MIDI's proven clamps do, and
# leaves the rest in place; the guard covers every stock byte it skips.
POINTERS = (
    (0x4001d882, 0x400e201c, 'modwerk_cfg_fs'),
    (0x4001d88a, 0x400e203c, 'modwerk_cfg_hs'),
    (0x4001d8c0, 0x400e207c, 'modwerk_cfg_os_hs'),
    (0x4001d8c8, 0x400e205c, 'modwerk_cfg_os_fs'),
)
CLAMP_SHA256 = 'ec1f697431abb21cc32bb4399935d28cfa9032e400b7e9b6a30811a764055e52'
DETOURS = (  # address, guarded bytes, their SHA-256, shim; 6 bytes are replaced
    (0x4001d858, 12, CLAMP_SHA256, 'modwerk_usb_clamp1'),
    (0x4001d896, 12, CLAMP_SHA256, 'modwerk_usb_clamp2'),
    (0x4001de64, 6, '868378f30d4ed1251a28851782180b919dbfbd18ea839b594142244f6e06fb8a', 'modwerk_ep0_shim'),
)


def endpoint(address, size):
    return bytes([7, 5, address, 2]) + struct.pack('<H', size) + bytes([0])


def configuration(high_speed, other_speed=False):
    """One configuration descriptor; bulk endpoints are 512 bytes at high speed."""
    bulk = 512 if high_speed else 64
    body = (bytes([9, 4, MSC_INTERFACE, 0, 2, 8, 6, 0x50, 0]) + endpoint(0x81, bulk) + endpoint(0x01, bulk) +
            bytes([9, 4, VENDOR_INTERFACE, 0, 0, VENDOR_CLASS, VENDOR_SUBCLASS, VENDOR_PROTOCOL, 0]))
    return (bytes([9, 7 if other_speed else 2]) + struct.pack('<H', 9 + len(body)) +
            bytes([2, 1, 0, 0xc0, 3]) + body)


def tables():
    return {'modwerk_cfg_fs': configuration(False), 'modwerk_cfg_hs': configuration(True),
            'modwerk_cfg_os_fs': configuration(False, True), 'modwerk_cfg_os_hs': configuration(True, True)}


ASSEMBLY = '''| usb_base.s -- generated by sdk/machines/octatrack/elekloader/usb_base.py.
| The base's configuration descriptors, the responder's length clamps and the
| unknown-request shim that hands vendor requests to modwerk_ep0_dispatch.
    .text
    .set modwerk_cfg_len, {length}

| GET_DESCRIPTOR(CONFIG / OTHER_SPEED): the stock clamps hold 32 bytes. Each
| shim leaves d1 = min(wLength, modwerk_cfg_len) as the stock 12 bytes would
| and rejoins after them. d2 = wLength.
    .global modwerk_usb_clamp1, modwerk_usb_clamp2
modwerk_usb_clamp1:
    movel   %d2,%d1
    cmpil   #modwerk_cfg_len,%d1
    blss    1f
    movel   #modwerk_cfg_len,%d1
1:  jmp     0x4001d864
modwerk_usb_clamp2:
    movel   %d2,%d1
    cmpil   #modwerk_cfg_len,%d1
    blss    1f
    movel   #modwerk_cfg_len,%d1
1:  jmp     0x4001d8a2

| The unknown-request tail, in the USB ISR. d0 is dead here (the displaced
| instruction overwrites it); keep the other scratch registers C may use.
| modwerk_ep0_dispatch returns a length to send modwerk_ep0_reply through
| the stock send tail (jsr usb_ep0_send(len, buf); addq #8; done), as USB
| Audio's shim does; 0 for a request that is not ours, which takes the stock
| STALL (IN only); or -1 to refuse one of ours. A refusal stalls EP0 both
| ways (TXS|RXS): the stock IN-only stall would leave a SUBMIT data stage
| NAKed until the host gives up. The next SETUP clears both bits.
    .global modwerk_ep0_shim
modwerk_ep0_shim:
    lea     %sp@(-12),%sp
    moveml  %d1/%a0-%a1,%sp@
    jsr     modwerk_ep0_dispatch
    moveml  %sp@,%d1/%a0-%a1
    lea     %sp@(12),%sp
    tstl    %d0
    beqs    2f
    moveq   #-1,%d1
    cmpl    %d1,%d0
    beqs    3f
    movel   modwerk_ep0_reply,%sp@-
    movel   %d0,%sp@-
    jmp     0x4001de5c
2:  movel   0xfc0b01c0,%d0
    jmp     0x4001de6a
3:  movel   0xfc0b01c0,%d0
    orl     #0x00010001,%d0
    movel   %d0,0xfc0b01c0
    jmp     0x4001de74

| One table per speed and direction. usb_ep0_send fills only the first page
| of its transfer descriptor, so 64-byte alignment keeps each in one 4 KiB page.
'''


def assembly():
    blobs = tables()
    lengths = {len(blob) for blob in blobs.values()}
    if len(lengths) != 1 or max(lengths) > 64:
        raise ValueError('The four configurations must share one length within one 64-byte slot.')
    text = ASSEMBLY.format(length=lengths.pop())
    for name, blob in blobs.items():
        text += '    .balign 64\n    .global %s\n%s:\n    .byte %s\n' % (name, name, ', '.join('0x%02x' % b for b in blob))
    return text


def header():
    return ('/* Generated by usb_base.py: the vendor interface this base declares. */\n'
            '#define MODWERK_VENDOR_INTERFACE %du\n#define MODWERK_MODEL "%s"\n' % (VENDOR_INTERFACE, MODEL))


def sites(image_at):
    """Elekloader sites after checking every stock span this base replaces or skips."""
    out = []
    for addr, expected, symbol in POINTERS:
        stock = image_at(addr, 4)
        if stock != expected.to_bytes(4, 'big'):
            raise ValueError('USB configuration pointer at 0x%08x is not stock.' % addr)
        out.append(dict(addr=hex(addr), stock=stock.hex(), op='ptr', target=symbol))
    for addr, length, digest, symbol in DETOURS:
        if hashlib.sha256(image_at(addr, length)).hexdigest() != digest:
            raise ValueError('USB site at 0x%08x is not stock.' % addr)
        out.append(dict(addr=hex(addr), stock=image_at(addr, 6).hex(), op='jmp', target=symbol))
    return out
