// Digitakt / Digitone modules for the website, from their module folders (contract v3).
// Memory is each mod's code and data from its author's release build; every linked mod shares the core's area.
// These are estimates: the linker's own checks (alignment, tables, overlap) decide whether a set builds.
import type { ModuleCategory } from '../catalog/modules'
import MACHINE_MODULES from '../catalog/machine-modules.json'
import MACHINES from './machines.generated.json'
import type { MachineProfile } from './machine-contract'
import type { ModwerkModule } from '../catalog/module-contract-v3'
import type { ModuleContributor } from '../catalog/module-authors'
import { moduleReleasedAt } from '../catalog/module-releases'

export type DigiMod = {
  id: string
  device: 'digitakt' | 'digitone'
  title: string
  version: string
  updatedAt?: string
  author: string
  contributors?: readonly ModuleContributor[]
  repository: string
  license: string
  category: string
  libraryCategory: ModuleCategory
  // Standalone firmware replaces the whole OS image and never combines with other mods.
  exclusive?: boolean
  summary: string
  ramBytes: number
  claims: string[]
  releases: string[]
  patchSites: Partial<Record<string, { addr: string; len: number }[]>>
  hardware?: string
}

// The Modwerk core is not built yet; until it is measured, the estimate reserves room for it.
export const CORE_RESERVE_BYTES = 4096
const profile = (id: DigiMod['device']) => (MACHINES as MachineProfile[]).find(machine => machine.id === id)!.sdk!
export const DIGI_CORES: Record<DigiMod['device'], { version: string; ramBytes: number; areaBytes: number; slots: string }> = Object.fromEntries((['digitakt', 'digitone'] as const).map(id => {
  const sdk = profile(id)
  return [id, { version: sdk.core?.version ?? '', ramBytes: CORE_RESERVE_BYTES, areaBytes: sdk.budgets.find(budget => budget.name === 'Shared mod memory')!.value, slots: sdk.budgets.filter(budget => budget.unit === 'slots').map(budget => budget.value + ' ' + budget.name.toLowerCase()).join(' · ') }]
})) as Record<DigiMod['device'], { version: string; ramBytes: number; areaBytes: number; slots: string }>

// Generated by npm run modules:generate from sdk/<machine>/modules/<id>/modwerk.module.json.
export const DIGI_MODS: DigiMod[] = (MACHINE_MODULES.modules as (ModwerkModule & Pick<DigiMod, 'patchSites'>)[]).map(module => ({
  id: module.id, device: module.machine as DigiMod['device'], title: module.name, version: module.version.split('-')[0],
  updatedAt: moduleReleasedAt(module.machine + '-' + module.id, module.version),
  author: module.author.name ?? module.author.github, repository: module.source?.repository ?? 'https://github.com/' + module.author.github,
  contributors: module.author.contributors,
  license: module.license.spdx, category: module.presentation.family, libraryCategory: module.category, summary: module.presentation.summary,
  ramBytes: module.resources.memoryBytes ?? 0, claims: module.platform.claims, exclusive: module.exclusive,
  releases: module.compatibility.releases, patchSites: module.patchSites,
  hardware: module.evidence.hardware ? module.evidence.hardware.summary : undefined,
}))

export type DigiEstimate = { usedBytes: number; areaBytes: number; fits: boolean; compatibleReleases: string[]; clashes: { claim: string; mods: string[] }[] }

export function estimateCombination(device: DigiMod['device'], ids: string[], release?: string): DigiEstimate {
  const core = DIGI_CORES[device]
  const mods = DIGI_MODS.filter(mod => mod.device === device && ids.includes(mod.id))
  const owners = new Map<string, string[]>()
  for (const mod of mods) for (const claim of mod.claims) owners.set(claim, [...(owners.get(claim) ?? []), mod.title])
  const usedBytes = mods.reduce((sum, mod) => sum + mod.ramBytes, mods.some(mod => mod.exclusive) ? 0 : core.ramBytes)
  const clashes = [...owners].filter(([, names]) => names.length > 1).map(([claim, names]) => ({ claim, mods: names }))
  const standalone = mods.find(mod => mod.exclusive)
  if (standalone && mods.length > 1) clashes.push({ claim: 'the whole OS (standalone firmware)', mods: mods.map(mod => mod.title) })
  const releases = (MACHINES as MachineProfile[]).find(machine => machine.id === device)!.firmware!.releases
    .map(item => item.version).filter(version => (!release || version === release) && mods.every(mod => mod.releases.includes(version)))
  const patchClashes = new Map<string, { claim: string; mods: string[] }[]>()
  for (const version of releases) {
    const pairs: { claim: string; mods: string[] }[] = []
    for (let i = 0; i < mods.length; i++) for (let j = i + 1; j < mods.length; j++) {
      const a = mods[i], b = mods[j]
      if ((a.patchSites[version] ?? []).some(site => (b.patchSites[version] ?? []).some(other => {
        const lo = Number(site.addr), otherLo = Number(other.addr)
        return lo < otherLo + other.len && otherLo < lo + site.len
      }))) pairs.push({ claim: 'overlapping firmware changes in OS ' + version, mods: [a.title, b.title] })
    }
    patchClashes.set(version, pairs)
  }
  const compatibleReleases = releases.filter(version => !patchClashes.get(version)!.length)
  if (!releases.length) clashes.push({ claim: 'no shared supported OS release', mods: mods.map(mod => mod.title) })
  else if (!compatibleReleases.length) clashes.push(...[...patchClashes.values()].flat())
  return { usedBytes, areaBytes: core.areaBytes, fits: usedBytes <= core.areaBytes, compatibleReleases: clashes.length ? [] : compatibleReleases, clashes }
}

export const DIGI_DEVICES = Object.keys(DIGI_CORES) as DigiMod['device'][]
export function isDigiDevice(id: string): id is DigiMod['device'] { return (DIGI_DEVICES as string[]).includes(id) }

export function categorySlug(category: string) { return category.toLowerCase() }

export function resolveDigiSelection(device: DigiMod['device'], ids: readonly string[]): DigiMod[] {
  const mods = DIGI_MODS.filter(mod => mod.device === device)
  const unknown = ids.filter(id => !mods.some(mod => mod.id === id))
  if (unknown.length) throw new Error('Unknown module: ' + unknown.join(', '))
  return mods.filter(mod => ids.includes(mod.id))
}

/** Keep the complete documentation available to detail pages; library cards use DigiMod's summary. */
export function digiModuleDocument(mod: Pick<DigiMod, 'device' | 'id'>): ModwerkModule {
  const document = (MACHINE_MODULES.modules as ModwerkModule[]).find(document => document.machine === mod.device && document.id === mod.id)
  if (!document) throw new Error('Unknown module: ' + mod.device + '/' + mod.id)
  return document
}
