; CYCLES_FORWARD_BRANCHES
; E-Verb (everb): a four-line modulated feedback delay network reverb for FX2,
; written from Tom Erbe, "Building the Erbe-Verb: Extending the Feedback Delay
; Network Reverb for Modular Synthesizer Use", ICMC 2015 (CC BY 3.0). Original
; implementation; no code, constants or tables from any other reverb.
; Generated by generate.py in this folder; edit that file, not this one.
;
; Per frame pair (44.1 kHz): L+R -> elliptic halfband decimator -> one tank tick at
; 22.05 kHz -> halfband interpolator -> equal-power mix with the untouched dry
; frames. Tank tick: pre-delay or reverse -> four lines, each an in-loop allpass
; (diffusion) into a modulated delay, absorb low-pass, decay gain and cubic
; saturation, into a 4x4 Hadamard matrix and back. Taps: line outputs and the
; allpass outputs (early reflections), then three-band tilt and wet gain.
; Even frames (A) read the tank, odd frames (B) write it: the two arms are a
; MODEFORK, so cycle_count.py prices each frame at the dearer arm.
;
; Ring: the 16K Y allocator buffer, one head r5 (m5 = 16383), segments below it:
;   pre   writes at r5    +0
;   ap0   writes at r5 -5515
;   ap1   writes at r5 -5799
;   ap2   writes at r5 -6041
;   ap3   writes at r5 -6243
;   ln0   writes at r5 -6409
;   ln1   writes at r5 -9575
;   ln2   writes at r5-12237
;   ln3   writes at r5-14477
;   16369 of 16384 words.
; X block r7+0..126, every word cleared by init:
;   0 base, 1 head, 2 clr, 3 ph, 4 frac, 5 gp, 6 dp, 7 jprev, 8 rng, 9 sigt
;   10 tau4, 11 omw, 12 grp, 13 us, 14 dz0, 15 dz1, 16 p1, 17 d, 18 fv0
;   19 fv1, 20 fv2, 21 fv3, 22 fv4, 23 fv5, 24 fv6, 25 v_S, 26 d_S, 27 v_G
;   28 d_G, 29 v_clp, 30 d_clp, 31 v_c2, 32 d_c2, 33 v_e, 34 d_e, 35 kosc
;   36 sx, 37 cy, 38 ct0, 39 ct1, 40 ct2, 41 ct3, 42 rnew0, 43 rnew1
;   44 rnew2, 45 rnew3, 46 rold0, 47 rold1, 48 rold2, 49 rold3, 50 yv0
;   51 yv1, 52 yv2, 53 yv3, 54 lw0, 55 lw1, 56 lw2, 57 lw3, 58 ll0, 59 ll1
;   60 ll2, 61 ll3, 62 er0, 63 g0, 64 er1, 65 er2, 66 g2, 67 er3, 68 lp0
;   69 lp1, 70 lp2, 71 lp3, 72 dc0, 73 dcx0, 74 dce0, 75 dc1, 76 dcx1
;   77 dce1, 78 f0, 79 f1, 80 f2, 81 f3, 82 sL, 83 sR, 84 dw0, 85 dw1
;   86 v_gap, 87 d_gap, 88 v_prel, 89 d_prel, 90 v_t0, 91 d_t0, 92 v_t1
;   93 d_t1, 94 v_t2, 95 d_t2, 96 v_dk, 97 d_dk, 98 dcin, 99 dcinx
;   100 dcine, 101 wL, 102 wR, 103 tlL, 104 txL, 105 thL, 106 tlR, 107 txR
;   108 thR, 109 iL0, 110 iL1, 111 iL2, 112 iR0, 113 iR1, 114 iR2, 115 jL0
;   116 jL1, 117 jR0, 118 jR1, 119 v_dgm1, 120 d_dgm1, 121 rho, 122 drho
;   123 rmode, 124 env, 125 t_S, 126 u_S

init:
        move    #>$ffffff,m4
        move    r7,r4
        clr     a
        do      #$84,>ev_izro
        move    a,x:(r4)+
ev_izro:
        nop
        move    x:>$213,r4              ; this instance's allocator entry
        move    x:(r4),a
        move    a,x:(r7+$0)
        move    a,x:(r7+$1)
        move    #>$80,a                 ; 128 calls of 128 words clear the ring
        move    a,x:(r7+$2)
        move    #>$79999a,a             ; quadrature oscillator amplitude
        move    a,x:(r7+$25)
        move    #>$5a5a5b,a             ; grain generator seed
        move    a,x:(r7+$8)
        move    #>$7fffff,a             ; the reverse duck starts open
        move    a,x:(r7+$60)
        move    #>$ffe6f7,a             ; line 0 write offset
        move    a,x:(r7+$36)
        move    #>$fff3a5,a             ; -3163
        move    a,x:(r7+$3a)
        move    #>$ffda99,a             ; line 1 write offset
        move    a,x:(r7+$37)
        move    #>$fff59d,a             ; -2659
        move    a,x:(r7+$3b)
        move    #>$ffd033,a             ; line 2 write offset
        move    a,x:(r7+$38)
        move    #>$fff743,a             ; -2237
        move    a,x:(r7+$3c)
        move    #>$ffc773,a             ; line 3 write offset
        move    a,x:(r7+$39)
        move    #>$fff89f,a             ; -1889
        move    a,x:(r7+$3d)
        rts

proc:
        move    a1,y0                           ; the dispatcher's flag: nonzero for a block's main call, 0 for a split sub-call
; Bounded clearing, 128 words per call: dry until the ring is clean.
        move    x:(r7+$2),a
        tst     a
        beq     ev_ready
        sub     #$1,a
        move    a,x:(r7+$2)
        asl     #$7,a,a
        move    x:(r7+$0),x0
        add     x0,a
        move    a,r4
        move    #>$ffffff,m4
        clr     a
        do      #128,>ev_clrd
        move    a,y:(r4)+
ev_clrd:
        nop
        rts
ev_ready:
; Smoothed values run v + delta*frac through a call (frac +1/32 per frame). Each call
; moves v to where the last one stopped; a main call then reads one of four knob
; groups and sets those deltas to (target - v)/8. Values glide continuously, split
; calls included, and every slope is refreshed every fourth block.
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    x:(r7+$4),y1
        clr     a
        move    a,x:(r7+$4)
        move    #>$2,n2
        lua     (r7+$19),r1
        lua     (r7+$19),r2
        move    x:(r1)+,a
        move    x:(r1)+,x0
        mac     x0,y1,a         x:(r1)+,b
        move    a,x:(r2)+n2
        move    x:(r1)+,x0
        mac     x0,y1,b         x:(r1)+,a
        move    b,x:(r2)+n2
        move    x:(r1)+,x0
        mac     x0,y1,a         x:(r1)+,b
        move    a,x:(r2)+n2
        move    x:(r1)+,x0
        mac     x0,y1,b         x:(r1)+,a
        move    b,x:(r2)+n2
        move    x:(r1)+,x0
        mac     x0,y1,a
        move    a,x:(r2)+n2
        move    r7,r1
        move    #>$56,n1
        lua     (r1+n1),r1
        move    r1,r2
        move    x:(r1)+,a
        move    x:(r1)+,x0
        mac     x0,y1,a         x:(r1)+,b
        move    a,x:(r2)+n2
        move    x:(r1)+,x0
        mac     x0,y1,b         x:(r1)+,a
        move    b,x:(r2)+n2
        move    x:(r1)+,x0
        mac     x0,y1,a         x:(r1)+,b
        move    a,x:(r2)+n2
        move    x:(r1)+,x0
        mac     x0,y1,b         x:(r1)+,a
        move    b,x:(r2)+n2
        move    x:(r1)+,x0
        mac     x0,y1,a         x:(r1)+,b
        move    a,x:(r2)+n2
        move    x:(r1)+,x0
        mac     x0,y1,b
        move    b,x:(r2)+n2
        move    r7,r1
        move    #>$77,n1
        lua     (r1+n1),r1
        move    r1,r2
        move    x:(r1)+,a
        move    x:(r1)+,x0
        mac     x0,y1,a
        move    a,x:(r2)+n2
; SIZE glides every delay, so its own glide is second order: u follows the target
; and the slope follows u, both on every call. A slope that changed only every fourth
; block would step the pitch of every line there (a block-rate zipper while SIZE moves).
        move    x:(r7+$7e),a
        move    x:(r7+$7d),b
        sub     a,b
        asr     #$3,b,b
        add     b,a                             ; u += (t - u)/8
        move    a,x:(r7+$7e)
        tfr     a,b
        move    x:(r7+$19),a
        sub     a,b
        asr     #$3,b,b
        move    b,x:(r7+$1a)                    ; slope (u - v)/8
        tfr     y0,a
        tst     a
        beq     ev_loop                         ; a split sub-call continues the ramps
        move    x:(r7+$c),a
        add     #$1,a
        and     #>$000003,a
        move    a1,x:(r7+$c)
        move    a1,x0
        tfr     x0,a
        tst     a
        beq     ev_gr0
        cmp     #$1,a
        beq     ev_gr1
        cmp     #$2,a
        beq     ev_gr2
        bra     ev_gr3
ev_gr0:
; envelope amounts: EDCY (slot 9), ESIZ (slot 10); envn = min(1, 4 env)
        move    x:(r7+$7c),a
        asl     #$2,a,a
        move    a,y1                            ; envn, limited
        move    x:(r6+$e),a
        and     #>$ff0000,a
        move    a1,x0
        tfr     x0,a
        sub     #>$400000,a                     ; v/128 - 1/2
        move    a,x0
        mpyi    #>$410410,x0,a
        asl     #$2,a,a
        move    a,x0                            ; t, limited
        tfr     x0,a
        mpy     x0,y1,b                         ; ESIZ env
        move    b,x:(r7+$35)
        move    x:(r6+$d),a
        and     #>$00ff00,a
        asl     #$8,a,a
        move    a1,x0
        tfr     x0,a
        sub     #>$400000,a                     ; v/128 - 1/2
        move    a,x0
        mpyi    #>$410410,x0,a
        asl     #$2,a,a
        move    a,x0                            ; t, limited
        tfr     x0,a
        mpy     x0,y1,b                         ; EDCY env
        move    b,x:(r7+$3e)
; SIZE (slot 0): u + ESIZ env in [0,1] -> S = 2^(-6(1-u)), six octaves
        move    x:(r6),x0
        mpyi    #>$408102,x0,a
        asl     a                               ; v/127
        move    x:(r7+$35),x0
        add     x0,a
        tst     a
        bge     ev_szlo
        clr     a
ev_szlo:
        move    a,x0                            ; u, limited at 1
        move    x0,x:(r7+$d)
        mpyi    #>$600000,x0,a
        sub     #>$600000,a                     ; v = 0.75u - 0.75
        bsr     ev_exq
        move    a,x0
        mpy     x0,x0,a
        tfr     a,b
        move    b,x:(r7+$7d)                    ; the target; every call glides toward it
; DCY (slot 1): u + EDCY env; g = 1 - (1 - 1.2u)^2 to 100% at u = 5/6, then 1.2u
; to 120%; G = 2g/3 drives the saturator
        move    x:(r6+$1),x0
        mpyi    #>$408102,x0,a
        asl     a                               ; v/127
; EDCY may lengthen the decay up to u = 0.75 (DCY 95, g = 0.99) but never into the
; sustain zone: only DCY itself goes there. u = min(u + EDCY env, max(u, 0.75))
        tfr     a,b
        move    #>$600000,x0
        cmp     x0,b
        tlt     x0,b                            ; max(u, 0.75)
        move    b,y1
        move    x:(r7+$3e),x0
        add     x0,a                            ; u + EDCY env
        cmp     y1,a
        tge     y1,a
        tst     a
        bge     ev_dclo
        clr     a
ev_dclo:
        move    a,x0                            ; u, limited at 1
        mpyi    #>$666666,x0,b                  ; G = 0.8u, the sustain zone
        mpyi    #>$4ccccd,x0,a
        asl     a                               ; 1.2u
        cmp     #>$7fffff,a
        bge     ev_dcsz
        neg     a
        add     #>$7fffff,a
        move    a,x0
        mpy     x0,x0,a
        neg     a
        add     #>$7fffff,a                     ; g
        move    a,x0
        mpyi    #>$555555,x0,b
ev_dcsz:
        move    #>$1b,n1
        bsr     ev_upd
        bra     ev_loop
ev_gr1:
; ABSB (slot 2): diffusion 0..0.8 up to 0.3, then damping d = (u-0.3)/0.7,
; absorb clp = 0.07 + 0.93 (1-d)^2
        move    x:(r6+$2),x0
        mpyi    #>$408102,x0,a
        asl     a                               ; v/127
        move    a,x:(r7+$35)
        move    a,x0
        mpyi    #>$555555,x0,b
        asl     #$2,b,b
        move    #>$666666,y1
        cmp     y1,b
        tge     y1,b
        move    #>$56,n1
        bsr     ev_upd
        move    x:(r7+$35),a
        sub     #>$266666,a
        tst     a
        bge     ev_dmlo
        clr     a
ev_dmlo:
        move    a,x0
        mpyi    #>$5b6db7,x0,a
        asl     a                               ; d
        neg     a
        add     #>$7fffff,a
        move    a,x0
        mpy     x0,x0,a                         ; (1-d)^2
        move    a,x0
        mpyi    #>$770a3d,x0,b
        add     #>$08f5c3,b
        move    #>$1d,n1
        bsr     ev_upd
; DPTH (slot 3), t: below 0 cyclic c = 0.9 t^2; to 0.75 ergodic e = 0.9 (t/0.75)^2;
; above, shimmer s = (t-0.75)/0.25 of the grains glide up an octave, e = 0.9 (1-s)
        move    x:(r6+$3),a
        sub     #>$400000,a                     ; v/128 - 1/2
        move    a,x0
        mpyi    #>$410410,x0,a
        asl     #$2,a,a
        move    a,x0                            ; t, limited
        tfr     x0,a
        move    a,x:(r7+$35)
        clr     b
        tst     a
        bge     ev_cyc0
        mpyi    #>$39999a,x0,a
        move    a,y0
        mpy     y0,x0,b                         ; c/2 = 0.45 t^2
ev_cyc0:
        move    #>$1f,n1
        bsr     ev_usn
        move    x:(r7+$35),a
        clr     b
        move    b,x:(r7+$9)
        tst     a
        ble     ev_erg0
        cmp     #>$600000,a
        bgt     ev_shim
        move    a,x0
        mpyi    #>$555555,x0,a
        asl     a
        move    a,x0                            ; t/0.75
        mpy     x0,x0,a
        move    a,x0
        mpyi    #>$733333,x0,b                  ; e
        bra     ev_erg0
ev_shim:
        sub     #>$600000,a
        asl     #$2,a,a
        move    a,x0                            ; s, limited at 1
; no new gliding grains until the cyclic depth has glided to exactly 0: a glide
; under a large cyclic offset would read ahead of its line
        move    x:(r7+$1f),b
        tst     b
        bne     ev_sblk
        move    x0,x:(r7+$9)
ev_sblk:
        move    #>$733333,b
        mpyi    #>$733333,x0,a
        sub     a,b                             ; e = 0.9 (1 - s)
ev_erg0:
        move    #>$21,n1
        bsr     ev_usn
; SPD (slot 4): f = 0.5 Hz 2^(9u): cyclic rotation and grain phase step; in the
; shimmer zone the grain lasts 0.75 L2 S ticks instead (SIZE sets it)
        move    x:(r6+$4),x0
        mpyi    #>$408102,x0,a
        asl     a                               ; v/127
        move    a,x0
        mpyi    #>$480000,x0,a
        asl     a
        sub     #>$7fffff,a                     ; v = (9u-9)/8
        bsr     ev_exq
        move    a,x0
        mpy     x0,x0,a
        move    a,x0                            ; f/256 Hz
        mpyi    #>$095659,x0,a
        move    a,x:(r7+$23)
        mpyi    #>194783,x0,a
        move    a1,x:(r7+$6)
        move    x:(r7+$9),a
        tst     a
        beq     ev_loop
        move    x:(r7+$d),x0
        mpyi    #>$a00000,x0,a
        bsr     ev_exq
        move    a,x0
        mpy     x0,x0,a
        move    a,x0                            ; 2^(-6u)
        mpyi    #>639989,x0,a
        move    a1,x:(r7+$6)
        bra     ev_loop
ev_gr2:
; PRE (slot 7): D = 154 * 2^(5.16u) samples (7..250 ms), as a fraction of 5512
        move    x:(r6+$c),a
        and     #>$00ff00,a
        asl     #$8,a,a
        move    a1,x0
        mpyi    #>$408102,x0,a
        asl     a                               ; v/127
        move    a,x:(r7+$35)
        move    a,x0
        mpyi    #>$5295ce,x0,a
        sub     #>$5295ce,a
        bsr     ev_exq
        move    a,x0
        mpy     x0,x0,a
        tfr     a,b
        move    #>$58,n1
        bsr     ev_upd
; reverse heads advance 2/W of the window per tick: drho = 2^25/154 * 2^(-5.16 max(u, u42))
        move    x:(r7+$35),a
        move    #>$402e50,x0
        cmp     x0,a
        tlt     x0,a
        move    a,x0
        mpyi    #>$ad6a32,x0,a
        bsr     ev_exq
        move    a,x0
        mpy     x0,x0,a
        move    a,x0
        mpyi    #>217886,x0,a
        move    a1,x:(r7+$7a)
; REV (slot 8): a change ducks the pre-delay output, switches at silence, reopens
        move    x:(r6+$d),a
        and     #>$ff0000,a
        move    a1,x0
        tfr     x0,a
        tst     a
        move    #>$1,x0
        tne     x0,a                            ; requested mode
        move    x:(r7+$7b),x0
        cmp     x0,a
        beq     ev_rvok
        move    a,x1
        move    x:(r7+$60),b
        cmp     #>$002000,b
        bge     ev_rvdk
        move    x1,x:(r7+$7b)                   ; closed: switch
        clr     a
        move    a,x:(r7+$79)
ev_rvdk:
        clr     b
        bra     ev_rvup
ev_rvok:
        move    #>$7fffff,b
ev_rvup:
        move    #>$60,n1
        bsr     ev_upd
        bra     ev_loop
ev_gr3:
; MIX (slot 5): equal power, wg = sin(pi m/2), dg = cos(pi m/2); 0 is the exact dry
        move    x:(r6+$5),x0
        mpyi    #>$408102,x0,a
        asl     a                               ; v/127
        move    a,x:(r7+$3e)
        tst     a
        beq     ev_mxz                          ; MIX 0: no wet gains or tilt to work out
        bsr     ev_sin
        move    a,x0                            ; wet gain, limited at 1
        move    x0,x:(r7+$40)
        move    x:(r7+$3e),b
        move    #>$7fffff,a
        sub     b,a                             ; 1 - m
        bsr     ev_sin
        sub     #>$7fffff,a                     ; dg - 1
        tfr     a,b
        move    #>$77,n1
        bsr     ev_usn
; TILT (slot 6, SETUP A), t: lows below 250 Hz 2^(-2t) (+-12 dB), highs above 2 kHz 2^(4t)
; (-+24 dB), mids untouched: t0 = k wg, t1 = t0 (gL - 1), t2 = t0 (gH - 1), k = 3.5/64
        move    x:(r6+$c),a
        and     #>$ff0000,a
        move    a1,x0
        tfr     x0,a
        sub     #>$400000,a                     ; v/128 - 1/2
        move    a,x0
        mpyi    #>$410410,x0,a
        asl     #$2,a,a
        move    a,x0                            ; t, limited
        tfr     x0,a
        move    a,x:(r7+$35)
        sub     #>$7fffff,a
        asr     a
        bsr     ev_exq
        move    a,x0
        mpy     x0,x0,a
        move    a,x:(r7+$3e)                    ; gH/16
        move    x:(r7+$35),a
        add     #>$7fffff,a
        asr     a
        neg     a
        bsr     ev_exq
        move    a,x:(r7+$35)                    ; gL/4
        move    x:(r7+$40),x0
        mpyi    #>$070000,x0,b                  ; t0 = k wg
        move    b,x:(r7+$40)
        move    #>$5a,n1
        bsr     ev_usn
        move    x:(r7+$35),a
        sub     #>$200000,a                     ; (gL - 1)/4
        move    a,x0
        move    x:(r7+$40),y0
        mpy     y0,x0,b
        asl     #$2,b,b
        move    #>$5c,n1
        bsr     ev_usn
        move    x:(r7+$3e),a
        sub     #>$080000,a                     ; (gH - 1)/16
        move    a,x0
        move    x:(r7+$40),y0
        mpy     y0,x0,b
        asl     #$4,b,b
        move    #>$5e,n1
        bsr     ev_usn
        bra     ev_mxc
ev_mxz:
; MIX 0: the dry gain glides to exactly 1 and every wet gain to 0 (the same targets the
; full path computes there, for less: MIX 0 must not be the dearest setting)
        clr     b
        move    #>$77,n1
        bsr     ev_usn
        clr     b
        move    #>$5a,n1
        bsr     ev_usn
        clr     b
        move    #>$5c,n1
        bsr     ev_usn
        clr     b
        move    #>$5e,n1
        bsr     ev_usn
ev_mxc:
; the wet fully off and settled: clear the interpolators, so MIX 0 is bit-exact dry
        move    x:(r7+$5a),a
        abs     a
        move    x:(r7+$5b),b
        abs     b
        add     b,a
        move    x:(r7+$5c),b
        abs     b
        add     b,a
        move    x:(r7+$5d),b
        abs     b
        add     b,a
        move    x:(r7+$5e),b
        abs     b
        add     b,a
        move    x:(r7+$5f),b
        abs     b
        add     b,a
        tst     a
        bne     ev_loop
        clr     a
        move    a,x:(r7+$65)
        move    a,x:(r7+$66)
        move    a,x:(r7+$6d)
        move    a,x:(r7+$6e)
        move    a,x:(r7+$6f)
        move    a,x:(r7+$73)
        move    a,x:(r7+$74)
        move    a,x:(r7+$70)
        move    a,x:(r7+$71)
        move    a,x:(r7+$72)
        move    a,x:(r7+$75)
        move    a,x:(r7+$76)
        move    a,x:(r7+$67)
        move    a,x:(r7+$6a)
        move    a,x:(r7+$68)
        move    a,x:(r7+$6b)
        move    a,x:(r7+$69)
        move    a,x:(r7+$6c)
ev_loop:
        move    x:(r7+$1),r5
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m6
        move    #>$3fff,m5
        move    #>$3fff,m4
        move    #>$1,n0
        move    r7,r6
        move    #>$40,n6
        move    (r6)+n6                         ; r6 = r7 + 64: one-word access to the upper half
        do      n7,>ev_end
        move    x:(r7+$4),a
        add     #>$040000,a                     ; frac += 1/32 per frame
        move    a,x:(r7+$4)
        move    x:(r7+$3),b
        tst     b
; MODEFORK_BEGIN -- even frames read the tank (A), odd frames write it (B)
        bne     ev_armb
; MODEFORK_MID -- A: decimator path 0, modulation, line reads, absorb, decay,
; saturation, matrix; interpolator path 1
        move    x:(r0),a
        move    x:(r0+n0),x0
        add     x0,a
        lua     (r7+$e),r1
        asr     a               x:(r1)+,b       ; x = (L+R)/2 ; x[n-1]
        lua     (r7+$e),r2
        move    x:(r1)+,x0                      ; out[n-1]
        sub     x0,a            a,x:(r2)+       ; x - out[n-1] ; x[n-1] = x
        move    a,x0
        maci    #>$24c882,x0,b                  ; path 0
        move    x:(r1)+,y0                      ; path 1 of the odd frame
        add     y0,b            b,x:(r2)+       ; path 0 + path 1 ; out[n-1]
        asr     b               (r2)+           ; d ; skip p1
        move    b,x:(r2)+                       ; d; r2 -> the frame values
        move    x:(r7+$4),y1
        lua     (r7+$19),r1
        move    x:(r1)+,a
        move    x:(r1)+,x0
        mac     x0,y1,a         x:(r1)+,b       ; S
        move    x:(r1)+,x0
        mac     x0,y1,b         a,x:(r2)+       ; G ; S
        move    x:(r1)+,a
        move    x:(r1)+,x0
        mac     x0,y1,a         b,x:(r2)+       ; clp ; G
        move    x:(r1)+,b
        move    x:(r1)+,x0
        mac     x0,y1,b         a,x:(r2)+       ; c/2 ; clp
        move    x:(r1)+,a
        move    x:(r1)+,x0
        mac     x0,y1,a         b,x:(r2)+       ; e ; c/2
        move    a,x:(r2)+                       ; e; r1 -> kosc
        move    x:(r1)+,y0                      ; k
        move    x:(r1)+,a                       ; sx
        move    x:(r1)-,x0                      ; cy
        mac     -y0,x0,a        x0,b            ; sx -= k cy ; b = cy
        move    a,x0
        mac     y0,x0,b         a,x:(r1)+       ; cy += k sx ; sx
        move    b,x:(r1)+                       ; cy; r1 -> ct0
; ct_i = c/2 (1 +- s): lines take +sx, +cy, -sx, -cy
        move    x:(r7+$15),y1                   ; c/2
        mpy     x0,y1,a         b,x0            ; c/2 sx ; cy
        mpy     x0,y1,b         a,x1            ; c/2 cy ; c/2 sx
        tfr     y1,a            b,y0
        add     x1,a
        tfr     y1,a            a,x:(r1)+       ; ct0
        add     y0,a
        tfr     y1,a            a,x:(r1)+       ; ct1
        sub     x1,a
        tfr     y1,a            a,x:(r1)+       ; ct2
        sub     y0,a
        move    a,x:(r1)+                       ; ct3
; grain clock gp (24-bit wrap): line j = gp>>22 crossfades during its quarter;
; a new quarter latches a random position for line j (a gliding grain on 0 and 2).
        move    x:(r7+$5),a
        move    x:(r7+$6),x0
        add     x0,a
        move    a1,x1
        move    x1,x:(r7+$5)
        tfr     x1,b
        lsr     #$16,b
        move    b1,y0                           ; j
        move    y0,n2
        tfr     y0,b
        move    x:(r7+$7),x0
        cmp     x0,b
        beq     ev_nlat
        move    y0,x:(r7+$7)
        move    r7,r2
        lua     (r2+n2),r2
; xorshift 5/9/11 (full period on 24 bits)
        move    x:(r7+$8),a
        move    a1,x0
        asl     #$5,a,a
        eor     x0,a
        move    a1,x0
        lsr     #$9,a
        eor     x0,a
        move    a1,x0
        asl     #$b,a,a
        eor     x0,a
        move    a1,x:(r7+$8)
        move    a1,x1                           ; r
        btst    #0,y0                           ; odd lines never glide
        bcs     ev_lstt
        and     #>$000fff,a
        asl     #$b,a,a
        move    a1,x0
        tfr     x0,a
        move    x:(r7+$9),x0
        cmp     x0,a
        blt     ev_shfl                         ; a gliding grain: position 0, flag bit set
ev_lstt:
        tfr     x1,a
        lsr     a
        and     #>$fffffe,a                     ; a static grain: uniform position, flag clear
        bra     ev_lpos
ev_shfl:
        move    #>$1,a
ev_lpos:
        move    a1,x0
        move    x:(r2+$2a),a
        move    a,x:(r2+$2e)
        move    x0,x:(r2+$2a)
ev_nlat:
; tau = frac(4 gp); 1 - w with w = 3 tau^2 - 2 tau^3; tau/4
        move    x:(r7+$5),a
        asl     #$2,a,a
        lsr     a
        move    a1,x0                           ; tau
        mpy     x0,x0,a
        move    a,x1
        mpy     x1,x0,b
        sub     b,a
        asl     a
        add     x1,a                            ; w
        neg     a
        add     #>$7fffff,a
        move    a,x:(r7+$b)
        tfr     x0,b
        asr     #$2,b,b
        move    b,x:(r7+$a)
        move    x:(r7+$16),y1                   ; e
        lua     (r7+$2a),r1
        lua     (r7+$3e),r2
        move    x:(r1)+,x0                      ; r0
        mpy     x0,y1,a         x:(r1)+,x1      ; e r0 ; r1
        move    a,x:(r2)+
; a gliding grain on line 0 sheds K0 phase0 = 0.75 (L2/L0) S gp of the line
        clr     b
        btst    #0,x0
        bcc     ev_gz0
        move    x:(r7+$5),a
        lsr     a
        move    a1,x0                           ; line 0 phase
        move    x:(r7+$12),y0                   ; S
        mpyi    #>$43e521,y0,b
        move    b,y0
        mpy     y0,x0,b
ev_gz0:
        move    b,x:(r2)+                       ; g0
        mpy     y1,x1,a         x:(r1)+,x0      ; e r1 ; r2
        mpy     x0,y1,b         a,x:(r2)+       ; e r2 ; er1
        move    b,x:(r2)+                       ; er2
; line 2: K2 phase2 = 0.75 S (gp - 1/2)
        clr     b
        btst    #0,x0
        bcc     ev_gz2
        move    x:(r7+$5),a
        add     #>$800000,a
        move    a1,x0
        tfr     x0,a
        lsr     a
        move    a1,x0                           ; line 2 phase
        move    x:(r7+$12),y0
        mpyi    #>$600000,y0,b
        move    b,y0
        mpy     y0,x0,b
ev_gz2:
        move    x:(r1)+,x0                      ; r3
        mpy     x0,y1,a         b,x:(r2)+       ; e r3 ; g2
        move    a,x:(r2)+                       ; er3
; heads: m = ct + e r ; u = S - S m (- glide) ; offset = W - u L ; interpolate
        move    x:(r7+$12),x1                   ; S, for all four
        lua     (r7+$26),r1
        lua     (r7+$3e),r2
        lua     (r7+$32),r3
        move    x:(r1)+,a                       ; ct0
        move    x:(r2)+,y0                      ; e r0
; line 0
        add     y0,a                            ; m
        tfr     x1,b            a,x0            ; S ; m
        mac     -x1,x0,b        x:(r2)+,y0      ; S - S m ; glide
        sub     y0,b                            ; u
; a glide never reads ahead of its line (cyclic depth can rise under it): u >= 2^-11
        move    #>$001000,x0
        cmp     x0,b
        tlt     x0,b
        move    b,x0
        move    #>$fff3a5,y0
        mpy     y0,x0,a
        add     #>$ffe6f7,a
        move    a1,n5
        move    a0,b1                           ; fraction (u >= 0 left the extension clear)
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1      ; psi ; s0
        move    b,x0            y:(r4),y0       ; psi ; s1
        mpy     y0,x0,a         x:(r1)+,b       ; next ct
        mac     -x0,y1,a        x:(r2)+,y0      ; next e r
        add     y1,a
; line 1
        add     y0,b            a,x:(r3)+       ; m ; line 0 head
        tfr     x1,a            b,x0            ; S ; m
        mac     -x1,x0,a                        ; u
        move    a,x0
        move    #>$fff59d,y0
        mpy     y0,x0,b
        add     #>$ffda99,b
        move    b1,n5
        move    b0,a1                           ; fraction (u >= 0 left the extension clear)
        lua     (r5+n5),r4
        lsr     a               y:(r4)+,y1      ; psi ; s0
        move    a,x0            y:(r4),y0       ; psi ; s1
        mpy     y0,x0,b         x:(r1)+,a       ; next ct
        mac     -x0,y1,b        x:(r2)+,y0      ; next e r
        add     y1,b
; line 2
        add     y0,a            b,x:(r3)+       ; m ; line 1 head
        tfr     x1,b            a,x0            ; S ; m
        mac     -x1,x0,b        x:(r2)+,y0      ; S - S m ; glide
        sub     y0,b                            ; u
; a glide never reads ahead of its line (cyclic depth can rise under it): u >= 2^-11
        move    #>$001000,x0
        cmp     x0,b
        tlt     x0,b
        move    b,x0
        move    #>$fff743,y0
        mpy     y0,x0,a
        add     #>$ffd033,a
        move    a1,n5
        move    a0,b1                           ; fraction (u >= 0 left the extension clear)
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1      ; psi ; s0
        move    b,x0            y:(r4),y0       ; psi ; s1
        mpy     y0,x0,a         x:(r1)+,b       ; next ct
        mac     -x0,y1,a        x:(r2)+,y0      ; next e r
        add     y1,a
; line 3
        add     y0,b            a,x:(r3)+       ; m ; line 2 head
        tfr     x1,a            b,x0            ; S ; m
        mac     -x1,x0,a                        ; u
        move    a,x0
        move    #>$fff89f,y0
        mpy     y0,x0,b
        add     #>$ffc773,b
        move    b1,n5
        move    b0,a1                           ; fraction (u >= 0 left the extension clear)
        lua     (r5+n5),r4
        lsr     a               y:(r4)+,y1      ; psi ; s0
        move    a,x0            y:(r4),y0       ; psi ; s1
        mpy     y0,x0,b
        mac     -x0,y1,b
        add     y1,b
        move    b,x:(r3)+                       ; line 3 head
; the line in its quarter keeps its old head, crossfaded out by 1 - w
        move    x:(r7+$7),n2
        move    r7,r2
        lua     (r2+n2),r2
        move    x:(r2+$26),a
        move    x:(r7+$16),y1                   ; e
        move    x:(r2+$2e),y0
        mac     y1,y0,a                         ; m old
        tfr     x1,b            a,x0
        mac     -x1,x0,b                        ; u old
        btst    #0,y0                           ; was it a gliding grain?
        bcc     ev_nko
        move    x:(r7+$12),y1
        mpyi    #>$43e521,y1,a
        move    x:(r7+$7),x0
        btst    #1,x0
        bcc     ev_kj0
        mpyi    #>$600000,y1,a                  ; line 2
ev_kj0:
        sub     a,b                             ; - K
        move    a,x0
        move    x:(r7+$a),y0
        mac     -y0,x0,b                        ; - K tau/4: the old grain glides on
ev_nko:
        move    #>$001000,x0
        cmp     x0,b
        tlt     x0,b                            ; u old >= 2^-11, as the new heads
        move    b,x0
        move    x:(r2+$3a),y0
        mpy     y0,x0,a
        move    x:(r2+$36),y0
        add     y0,a
        move    a1,n5
        move    a0,b1                           ; the fraction into a clean accumulator
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1      ; psi ; s0
        move    b,x0            y:(r4),y0       ; psi ; s1
        mpy     y0,x0,a
        mac     -x0,y1,a
        add     y1,a                            ; old head
        move    x:(r2+$32),b
        sub     b,a                             ; old - new
        move    a,x0
        move    x:(r7+$b),y0
        mac     y0,x0,b
        move    b,x:(r2+$32)
; absorb lp += clp (x - lp); lines 0 and 1 then block DC (exact zero, no dead
; band); h = 16 G x, s/2 = (0.375 h - 0.125 h^3)/2 into the matrix
        move    x:(r7+$14),y0                   ; clp
        move    x:(r7+$13),y1                   ; G
        lua     (r7+$32),r1
        lua     (r6+$4),r2
        lua     (r6+$e),r3
; line 0
        move    x:(r1),a                        ; x
        move    x:(r2),b                        ; lp
        sub     b,a
        move    a,x0
        mac     y0,x0,b                         ; lp
        move    b,x:(r2)+
        move    x:(r6+$9),x0                    ; x[n-1]
        move    b,x:(r6+$9)
        sub     x0,b                            ; x - x[n-1]
        move    x:(r6+$a),b0                    ; the remainder
        move    x:(r6+$8),x0                    ; y[n-1]
        maci    #>$7fc7fa,x0,b
        move    b0,x:(r6+$a)
        move    b,x:(r6+$8)
        move    b,x0
        mpy     x0,y1,a                         ; G x
        asl     #$4,a,a                         ; h = 16 G x
        move    a,x0                            ; limits to +-1
        mpy     x0,x0,b         b,x:(r1)+       ; h^2 ; the tap
        move    b,x1
        mpy     x1,x0,b                         ; h^3
        move    b,x1
        mpyi    #>$060000,x0,a
        maci    #>$fe0000,x1,a
        move    a,x:(r3)+                       ; s/2
; line 1
        move    x:(r1),a                        ; x
        move    x:(r2),b                        ; lp
        sub     b,a
        move    a,x0
        mac     y0,x0,b                         ; lp
        move    b,x:(r2)+
        move    x:(r6+$c),x0                    ; x[n-1]
        move    b,x:(r6+$c)
        sub     x0,b                            ; x - x[n-1]
        move    x:(r6+$d),b0                    ; the remainder
        move    x:(r6+$b),x0                    ; y[n-1]
        maci    #>$7fc7fa,x0,b
        move    b0,x:(r6+$d)
        move    b,x:(r6+$b)
        move    b,x0
        mpy     x0,y1,a                         ; G x
        asl     #$4,a,a                         ; h = 16 G x
        move    a,x0                            ; limits to +-1
        mpy     x0,x0,b         b,x:(r1)+       ; h^2 ; the tap
        move    b,x1
        mpy     x1,x0,b                         ; h^3
        move    b,x1
        mpyi    #>$060000,x0,a
        maci    #>$fe0000,x1,a
        move    a,x:(r3)+                       ; s/2
; line 2
        move    x:(r1),a                        ; x
        move    x:(r2),b                        ; lp
        sub     b,a
        move    a,x0
        mac     y0,x0,b                         ; lp
        move    b,x0
        mpy     x0,y1,a         b,x:(r2)+       ; G x ; lp
        asl     #$4,a,a                         ; h = 16 G x
        move    a,x0                            ; limits to +-1
        mpy     x0,x0,b         b,x:(r1)+       ; h^2 ; the tap
        move    b,x1
        mpy     x1,x0,b                         ; h^3
        move    b,x1
        mpyi    #>$060000,x0,a
        maci    #>$fe0000,x1,a
        move    a,x:(r3)+                       ; s/2
; line 3
        move    x:(r1),a                        ; x
        move    x:(r2),b                        ; lp
        sub     b,a
        move    a,x0
        mac     y0,x0,b                         ; lp
        move    b,x0
        mpy     x0,y1,a         b,x:(r2)+       ; G x ; lp
        asl     #$4,a,a                         ; h = 16 G x
        move    a,x0                            ; limits to +-1
        mpy     x0,x0,b         b,x:(r1)+       ; h^2 ; the tap
        move    b,x1
        mpy     x1,x0,b                         ; h^3
        move    b,x1
        mpyi    #>$060000,x0,a
        maci    #>$fe0000,x1,a
        move    a,x:(r3)+                       ; s/2
; stereo taps: L = x0 - x2, R = x1 - x3
        lua     (r7+$32),r1
        move    x:(r1)+,a
        move    x:(r1)+,b
        move    x:(r1)+,x0
        sub     x0,a            x:(r1)+,x0
        sub     x0,b            a,x:(r3)+       ; R ; L (r3 -> sL)
        move    b,x:(r3)+                       ; R
; 4x4 Hadamard / 2 (the halving is in s/2)
        lua     (r6+$e),r1
        lua     (r6+$e),r2
        move    x:(r1)+,a                       ; s0
        move    x:(r1)+,x0                      ; s1
        tfr     a,b             x:(r1)+,y0      ; s2
        add     x0,a            x:(r1)+,y1      ; P = s0 + s1 ; s3
        sub     x0,b            a,x1            ; Q = s0 - s1 ; P
        tfr     y0,a            b,x0            ; Q
        add     y1,a                            ; R = s2 + s3
        tfr     y0,b            a,y0            ; R
        sub     y1,b                            ; T = s2 - s3
        tfr     x1,a            b,y1            ; T
        add     y0,a                            ; f0 = P + R
        tfr     x0,a            a,x:(r2)+
        add     y1,a                            ; f1 = Q + T
        tfr     x1,a            a,x:(r2)+
        sub     y0,a                            ; f2 = P - R
        tfr     x0,a            a,x:(r2)+
        sub     y1,a                            ; f3 = Q - T
        move    a,x:(r2)+
; interpolator path 1 (c1) on last tick's wet: the odd frame's output
        move    x:(r6+$25),a
        lua     (r6+$33),r1
        lua     (r6+$33),r2
        move    x:(r1)+,b                       ; x[n-1]
        move    x:(r1)+,x0                      ; out[n-1]
        sub     x0,a            a,x:(r2)+       ; x - out[n-1] ; x[n-1]
        move    a,x0
        maci    #>$3f88e3,x0,b
        move    b,x:(r2)+                       ; out (the odd frame reads it)
        move    x:(r6+$26),a
        lua     (r6+$35),r1
        lua     (r6+$35),r2
        move    x:(r1)+,b                       ; x[n-1]
        move    x:(r1)+,x0                      ; out[n-1]
        sub     x0,a            a,x:(r2)+       ; x - out[n-1] ; x[n-1]
        move    a,x0
        maci    #>$3f88e3,x0,b
        move    b,x:(r2)+                       ; out (the odd frame reads it)
        move    #>$1,a
        move    a,x:(r7+$3)
        move    x:(r6+$2f),x0                   ; this frame: path 0 of the last tick
        move    x:(r6+$32),x1
        bra     ev_join
; MODEFORK_MID -- B: decimator path 1, pre-delay or reverse, four allpasses and
; line writes, early taps, envelope, tilt; interpolator path 0
ev_armb:
        move    x:(r0),a
        move    x:(r0+n0),x0
        add     x0,a
        lua     (r6+$14),r1
        asr     a               x:(r1)+,b       ; x ; x[n-1]
        lua     (r6+$14),r2
        move    x:(r1)+,x0                      ; out[n-1]
        sub     x0,a            a,x:(r2)+       ; x - out[n-1] ; x[n-1]
        move    a,x0
        maci    #>$61f738,x0,b                  ; path 1
        move    b,x:(r2)+
        move    b,x:(r7+$10)                    ; for the next even frame
        move    x:(r7+$4),y1
        lua     (r6+$16),r1
        lua     (r7+$13),r2
        move    x:(r1)+,a
        move    x:(r1)+,x0
        mac     x0,y1,a         x:(r1)+,b       ; gap
        move    x:(r1)+,x0
        mac     x0,y1,b         a,x:(r2)+       ; prel ; gap
        move    x:(r1)+,a
        move    x:(r1)+,x0
        mac     x0,y1,a         b,x:(r2)+       ; t0 ; prel
        move    x:(r1)+,b
        move    x:(r1)+,x0
        mac     x0,y1,b         a,x:(r2)+       ; t1 ; t0
        move    x:(r1)+,a
        move    x:(r1)+,x0
        mac     x0,y1,a         b,x:(r2)+       ; t2 ; t1
        move    x:(r1)+,b
        move    x:(r1)+,x0
        mac     x0,y1,b         a,x:(r2)+       ; dk ; t2
        move    b,x:(r2)+                       ; dk
        move    x:(r7+$11),a
        move    a,y:(r5)                        ; the pre-delay write
        move    x:(r6+$3b),b
        tst     b
        bne     ev_rvrs
        move    x:(r7+$14),x0                   ; D/5512
        move    #>$ffea78,y0
        mpy     y0,x0,a
        move    a1,n5
        move    a0,b1                           ; the fraction into a clean accumulator
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1      ; psi ; s0
        move    b,x0            y:(r4),y0       ; psi ; s1
        mpy     y0,x0,a
        mac     -x0,y1,a
        add     y1,a                            ; q
        bra     ev_pred
ev_rvrs:
; reverse: two heads sweep back through W = max(D, 42 ms), smoothstep crossfade.
; head offset = -(2 + phase (W-4)), the phase a 24-bit wrap stepped 2/W per tick
        move    x:(r7+$14),a
        move    #>$1580ee,x0
        cmp     x0,a
        tlt     x0,a
        sub     #>$0017c8,a                     ; uw = (W - 4)/5512
        move    a,x0
        mpyi    #>$ffea78,x0,a                  ; -(W - 4), whole samples
        move    a1,x:(r6+$1)
        move    x:(r6+$39),a
        move    x:(r6+$3a),x0
        add     x0,a
        move    a1,x1                           ; rho
        move    x1,x:(r6+$39)
        tfr     x1,a
        abs     a                               ; triangle
        move    a,x0                            ; limits at 1
        mpy     x0,x0,a
        move    a,y0
        mpy     y0,x0,b
        sub     b,a
        asl     a
        add     y0,a                            ; head A weight
        move    a,x:(r7+$3f)
        tfr     x1,a
        lsr     a
        move    a1,x0                           ; head A phase
        move    x:(r6+$1),y1
        mpy     x0,y1,a                         ; -phase (W-4)
        sub     #$2,a
        clr     b
        move    a1,n5
        move    a0,b1                           ; the fraction into a clean accumulator
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1      ; psi ; s0
        move    b,x0            y:(r4),y0       ; psi ; s1
        mpy     y0,x0,a
        mac     -x0,y1,a
        add     y1,a                            ; head A
        move    a,x:(r7+$3e)
        move    x:(r6+$39),a
        add     #>$800000,a
        move    a1,x0
        tfr     x0,a
        lsr     a
        move    a1,x0                           ; head B phase
        move    x:(r6+$1),y1
        mpy     x0,y1,a                         ; -phase (W-4)
        sub     #$2,a
        clr     b
        move    a1,n5
        move    a0,b1                           ; the fraction into a clean accumulator
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1      ; psi ; s0
        move    b,x0            y:(r4),y0       ; psi ; s1
        mpy     y0,x0,a
        mac     -x0,y1,a
        add     y1,a                            ; head B
        tfr     a,b                             ; B
        move    x:(r7+$3e),a
        sub     b,a                             ; A - B
        move    a,x0
        move    x:(r7+$3f),y0
        mac     y0,x0,b
        tfr     b,a                             ; q = B + wA (A - B)
ev_pred:
; duck (REV switching), input DC block, qi = q/8 (the allpass inputs are quartered)
        move    a,x0
        move    x:(r7+$18),y0                   ; duck
        mpy     y0,x0,a
        move    x:(r6+$23),x0
        move    a,x:(r6+$23)
        sub     x0,a
        move    x:(r6+$24),a0
        move    x:(r6+$22),x0
        maci    #>$7fa2a1,x0,a
        move    a0,x:(r6+$24)
        move    a,x:(r6+$22)
        move    a,x0
        mpyi    #>$100000,x0,a
        move    x:(r7+$12),x1                   ; S from the even frame
        move    a,x:(r7+$12)                    ; qi, beside g
; allpass i: Wd at a_i S; W' = v/4 + g Wd ; y/4 = Wd - g W' into the line
        lua     (r6+$e),r1
        lua     (r7+$26),r2
        lua     (r7+$12),r3
; line 0
        move    #>$fffee7,y0
        mpy     x1,y0,a                         ; -a S
        add     #>$ffea75,a
        clr     b
        move    a1,n5
        move    a0,b1
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1
        move    b,x0            y:(r4),y0
        mpy     y0,x0,a
        mac     -x0,y1,a
        add     y1,a            x:(r3)+,x0      ; Wd ; qi
        move    x:(r1)+,b       a,y0            ; f/4 ; Wd
        add     x0,b            x:(r3)-,x0      ; v/4 ; g
        mac     y0,x0,b                         ; W'
        move    #>$ffea75,n5
        move    b,y:(r5+n5)
        tfr     y0,a            b,y1
        mac     -x0,y1,a                        ; y/4
        move    #>$ffe6f7,n5
        move    a,y:(r5+n5)
        move    a,x:(r2)+                       ; early tap
; line 1
        move    #>$ffff11,y0
        mpy     x1,y0,a                         ; -a S
        add     #>$ffe959,a
        clr     b
        move    a1,n5
        move    a0,b1
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1
        move    b,x0            y:(r4),y0
        mpy     y0,x0,a
        mac     -x0,y1,a
        add     y1,a            x:(r3)+,x0      ; Wd ; qi
        move    x:(r1)+,b       a,y0            ; f/4 ; Wd
        add     x0,b            x:(r3)-,x0      ; v/4 ; g
        mac     y0,x0,b                         ; W'
        move    #>$ffe959,n5
        move    b,y:(r5+n5)
        tfr     y0,a            b,y1
        mac     -x0,y1,a                        ; y/4
        move    #>$ffda99,n5
        move    a,y:(r5+n5)
        move    a,x:(r2)+                       ; early tap
; line 2
        move    #>$ffff39,y0
        mpy     x1,y0,a                         ; -a S
        add     #>$ffe867,a
        clr     b
        move    a1,n5
        move    a0,b1
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1
        move    b,x0            y:(r4),y0
        mpy     y0,x0,a
        mac     -x0,y1,a
        add     y1,a            x:(r3)+,x0      ; Wd ; qi
        move    x:(r1)+,b       a,y0            ; f/4 ; Wd
        add     x0,b            x:(r3)-,x0      ; v/4 ; g
        mac     y0,x0,b                         ; W'
        move    #>$ffe867,n5
        move    b,y:(r5+n5)
        tfr     y0,a            b,y1
        mac     -x0,y1,a                        ; y/4
        move    #>$ffd033,n5
        move    a,y:(r5+n5)
        move    a,x:(r2)+                       ; early tap
; line 3
        move    #>$ffff5d,y0
        mpy     x1,y0,a                         ; -a S
        add     #>$ffe79d,a
        clr     b
        move    a1,n5
        move    a0,b1
        lua     (r5+n5),r4
        lsr     b               y:(r4)+,y1
        move    b,x0            y:(r4),y0
        mpy     y0,x0,a
        mac     -x0,y1,a
        add     y1,a            x:(r3)+,x0      ; Wd ; qi
        move    x:(r1)+,b       a,y0            ; f/4 ; Wd
        add     x0,b            x:(r3)-,x0      ; v/4 ; g
        mac     y0,x0,b                         ; W'
        move    #>$ffe79d,n5
        move    b,y:(r5+n5)
        tfr     y0,a            b,y1
        mac     -x0,y1,a                        ; y/4
        move    #>$ffc773,n5
        move    a,y:(r5+n5)
        move    a,x:(r2)+                       ; early tap
; wet = taps + 0.5 (allpass outputs): L takes y0 - y3, R y1 - y2
        lua     (r7+$26),r1
        move    x:(r1)+,a                       ; y0
        move    x:(r1)+,b                       ; y1
        move    x:(r1)+,x0                      ; y2
        sub     x0,b            x:(r1)+,x0      ; y1 - y2 ; y3
        sub     x0,a            b,y1
        move    a,y0
        move    x:(r6+$12),a
        maci    #>$400000,y0,a
        move    x:(r6+$13),b
        maci    #>$400000,y1,b
        move    a,x:(r6+$25)
        move    b,x:(r6+$26)
        abs     a
        abs     b
        add     b,a
        move    x:(r6+$3c),b
        sub     b,a
        move    a,x0
        maci    #>$002000,x0,b
        move    b,x:(r6+$3c)
; tilt: lo += k (w - lo) ; hi = bilinear high-pass ; y = 64 (t0 w + t1 lo + t2 hi)
        lua     (r6+$27),r1
        lua     (r6+$27),r2
        move    x:(r6+$25),a
        move    x:(r1)+,b                       ; lo
        sub     b,a             a,y1            ; w - lo ; y1 = w
        move    a,x0
        maci    #>$08cd1e,x0,b                  ; lo
        tfr     y1,a            b,x:(r2)+       ; w ; lo
        move    x:(r1)+,x0                      ; x[n-1]
        sub     x0,a            y1,x:(r2)+      ; w - x[n-1] ; x[n-1] = w
        move    a,x0
        mpyi    #>$63001f,x0,a
        move    x:(r1)+,x0                      ; hi[n-1]
        maci    #>$46003d,x0,a                  ; hi
        move    a,x:(r2)+
        move    a,x0
        move    x:(r7+$17),y0                   ; t2
        mpy     y0,x0,a
        move    x:(r7+$15),x0                   ; t0
        mac     x0,y1,a                         ; + t0 w
        move    b,x0                            ; lo
        move    x:(r7+$16),y0                   ; t1
        mac     y0,x0,a
        asl     #$6,a,a
        move    a,x:(r6+$25)                    ; the wet, limited
        move    x:(r6+$26),a
        move    x:(r1)+,b                       ; lo
        sub     b,a             a,y1            ; w - lo ; y1 = w
        move    a,x0
        maci    #>$08cd1e,x0,b                  ; lo
        tfr     y1,a            b,x:(r2)+       ; w ; lo
        move    x:(r1)+,x0                      ; x[n-1]
        sub     x0,a            y1,x:(r2)+      ; w - x[n-1] ; x[n-1] = w
        move    a,x0
        mpyi    #>$63001f,x0,a
        move    x:(r1)+,x0                      ; hi[n-1]
        maci    #>$46003d,x0,a                  ; hi
        move    a,x:(r2)+
        move    a,x0
        move    x:(r7+$17),y0                   ; t2
        mpy     y0,x0,a
        move    x:(r7+$15),x0                   ; t0
        mac     x0,y1,a                         ; + t0 w
        move    b,x0                            ; lo
        move    x:(r7+$16),y0                   ; t1
        mac     y0,x0,a
        asl     #$6,a,a
        move    a,x:(r6+$26)                    ; the wet, limited
; interpolator path 0 (c0, c2): the next even frame
        move    x:(r6+$25),a
        lua     (r6+$2d),r1
        lua     (r6+$2d),r2
        move    x:(r1)+,b
        move    x:(r1)+,x1
        sub     x1,a            a,x:(r2)+
        move    a,x0
        maci    #>$1488ad,x0,b
        move    x:(r1)+,x0
        tfr     x1,a            b,x:(r2)+
        sub     x0,b
        move    b,x0
        maci    #>$6a4e1e,x0,a
        move    a,x:(r2)+                       ; the even output
        move    x:(r6+$26),a
        lua     (r6+$30),r1
        lua     (r6+$30),r2
        move    x:(r1)+,b
        move    x:(r1)+,x1
        sub     x1,a            a,x:(r2)+
        move    a,x0
        maci    #>$1488ad,x0,b
        move    x:(r1)+,x0
        tfr     x1,a            b,x:(r2)+
        sub     x0,b
        move    b,x0
        maci    #>$6a4e1e,x0,a
        move    a,x:(r2)+                       ; the even output
        move    (r5)+                           ; the ring head moves one tick
        clr     a
        move    a,x:(r7+$3)
        move    x:(r6+$34),x0                   ; this frame: path 1 from the even frame
        move    x:(r6+$36),x1
; MODEFORK_END
ev_join:
; out = dry (1 + dgm1) + wet, dgm1 ramped per frame
        move    x:(r6+$37),b
        move    x:(r6+$38),y0
        move    x:(r7+$4),y1
        mac     y1,y0,b         x:(r0),y1       ; dgm1 ; L
        tfr     y1,a            b,y0
        mac     y1,y0,a
        add     x0,a
        move    a,x:(r0)+
        move    x:(r0),y1
        tfr     y1,a
        mac     y1,y0,a
        add     x1,a
        move    a,x:(r0)+
ev_end:
        nop
        move    r5,x:(r7+$1)
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m4
        move    #>$ffffff,m5
        move    #>$ffffff,m6
        rts

; Per-call subroutines. Only the knob groups call these, never the frame loop.
; ev_upd: b = target, n1 = the offset of v_p: d_p = (target - v_p)/8
ev_upd:
        move    r7,r1
        lua     (r1+n1),r1
        move    x:(r1)+,a                       ; now
        sub     a,b                             ; target - now
        asr     #$3,b,b
        move    b,x:(r1)
        rts
; ev_usn: the same, landing on the target when within 2^-13
ev_usn:
        move    r7,r1
        lua     (r1+n1),r1
        move    x:(r1),a                        ; now
        sub     a,b                             ; target - now
        move    b,x0
        abs     b
        cmp     #>$000400,b
        bge     ev_uglid
        add     x0,a                            ; close: land on it
        move    a,x:(r1)+
        clr     b
        move    b,x:(r1)
        rts
ev_uglid:
        tfr     x0,b
        asr     #$3,b,b
        move    b,x:(r1+$1)
        rts
; ev_exq: a = v in [-1.125, 0] -> a = (2^v)^4. Clobbers x0, y0.
ev_exq:
        move    a,x0
        mpyi    #>$04c630,x0,a
        add     #>$1d236d,a
        move    a,y0
        mpy     y0,x0,a
        add     #>$585767,a
        move    a,y0
        mpy     y0,x0,a
        add     #>$7ffc14,a
        move    a,x0
        mpy     x0,x0,a
        move    a,x0
        mpy     x0,x0,a
        rts
; ev_sin: a = m in [0, 1] -> a = sin(pi m/2). Clobbers x0, x1, y0.
ev_sin:
        move    a,x0
        mpy     x0,x0,a
        move    a,x1                            ; m^2
        mpyi    #>$0497e2,x1,a
        add     #>$d6e7b8,a
        move    a,y0
        mpy     x1,y0,a
        add     #>$648066,a
        move    a,y0
        mpy     y0,x0,a                         ; s/2
        asl     a
        rts
