; CYCLES_FORWARD_BRANCHES
; SHIMMER: stereo diffused FDN with overlapping-read pitch feedback.
; Original implementation 2026 Julius Sylvest / juliussylvest-lab, MIT.
; Allpass/Householder/glide idioms adapted from Mini Verb by Jannik Aßfalg
; and Sam Banks; original author credits and MIT terms retained in LICENSE.
; 44.1 kHz. Independent 16K allocator Y ring. No global writable state.
; init preserves r1/n1/m1 and clears every persistent scalar from dirty RAM.
; X r7:00..07/08..0f L/R antialias states,10..13 branch damping;
; 14/15 stock call flags are preserved,16/17 wetcolor LP,18/19 inputDC,
; 1a/1b outputDC,1c firstgrainread,1d window,1e dampingcoefficient,1f SIZEcarry;
; 20 base,21 head,22 clear,23 original pitch-table base;
; 24..29 targets TIME/SIZE/PTCH/SHMR/TONE/MIX,2a..2f respective runs;
; 30/31 inputHP then pitchreturns,32/33 inputdiffusers;
; 34..37 FDNtaps then normalizedblendedreturns,38/39 wetprojections;
; 3a mean,3b feedbackmean,3c/3d grainphase,3e first-ready;
; 3f/40 inputDC carry,41/42 outputDC carry (exact alpha=1/1024).
; init clears00..13 and16..7f (126words), preserving14/15.
; Only00..13/16..42 are referenced. No word at/above84 is touched.
; Ring intervals (write..furthest read, distance behind moving head):
; AP0..113/114..287/288..505/506..813;
; FDN814..2286/AP2287..2564, FDN2565..4168/AP4169..4590,
; FDN4591..6370/AP6371..6918, FDN6919..8920/AP8921..9604;
; pitch9605..11656/11657..13708. Remaining words are padding.
; Read phase is an audio-sample position, not a song/sequencer clock.
init:
        move    #>$ffffff,m4
        move    r7,r4
        clr     a
        do      #20,>sv_low_zero
        move    a,x:(r4)+
sv_low_zero:
        nop
        move    #>$2,n4
        move    (r4)+n4
        do      #106,>sv_high_zero
        move    a,x:(r4)+
sv_high_zero:
        nop
        move    #>$fab1e0,a
        move    a,x:(r7+$23)
        move    x:>$213,r4
        move    x:(r4),a
        move    a,x:(r7+$20)
        move    a,x:(r7+$21)
        move    #>$4000,x0
        cmp     x0,a
        bge     sv_allocated
        move    #>$ffffff,a
        move    a,x:(r7+$22)
        rts
sv_allocated:
        move    #>$80,a
        move    a,x:(r7+$22)
        move    #>$1,a
        move    a,x:(r7+$3e)
        move    #>$200000,a
        move    a,x:(r7+$3d)
        rts
proc:
; Progressive clearing: unchanged dry output until all 16K words are clean.
        move    x:(r7+$22),a
        tst     a
        beq     sv_ready
        bmi     sv_dry
        sub     #>$1,a
        move    a,x:(r7+$22)
        asl     #$7,a,a
        move    x:(r7+$20),x0
        add     x0,a
        move    a,r4
        move    #>$ffffff,m4
        clr     a
        do      #128,>sv_erase
        move    a,y:(r4)+
sv_erase:
        nop
sv_dry:
        rts
sv_ready:
; TIME g=.65+.335*(2*u-u*u), always below .985.
        move    x:(r6),x0
        move    x0,y1
        mpy     x0,y1,a
        move    x0,b
        asl     #$1,b,b
        sub     a,b
        move    b,x0
        move    #>$2ae148,y1
        mpy     x0,y1,a
        move    #>$533333,x0
        add     x0,a
        move    a,x:(r7+$24)
; SIZE .25 + .75*u.
        move    x:(r6+$1),x0
        move    #>$600000,y1
        mpy     x0,y1,a
        add     #>$200000,a
        move    a,x:(r7+$25)
; PTCH coordinate k/4 below64,16+(k-64)*16/63 above64. Table values
; are original (1-exp2(semitones/12))*4096*256, phase-increment Q8.
        move    x:(r6+$2),a
        move    #>$400000,x0
        cmp     x0,a
        ble     sv_lookup
        sub     x0,a
        move    a,x0
        move    #>$410410,y1
        mpy     x0,y1,a
        asl     #$1,a,a
        add     #>$400000,a
        move    a,x1
        move    x1,a
sv_lookup:
        move    a,x1
        asr     #$12,a,a
        move    a1,n4
        move    x:(r7+$23),r4
        move    (r4)+n4
        move    x1,a
        and     #>$3ffff,a
        asl     #$5,a,a
        move    a,x0
        move    p:(r4)+,y0
        move    p:(r4),b
        move    y0,a
        sub     a,b
        move    b,y1
        mpy     x0,y1,a
        add     y0,a
        move    a,x:(r7+$26)
        move    x:(r6+$3),a
        move    #>$7f0000,x0
        cmp     x0,a
        bne     sv_shmr_target
        move    #>$7fffff,a
sv_shmr_target:
        move    a,x:(r7+$27)
        move    x:(r6+$4),a
        cmp     x0,a
        beq     sv_bright
        sub     #>$400000,a
        asl     #$1,a,a
        bra     sv_tone_target
sv_bright:
        move    #>$7fffff,a
sv_tone_target:
        move    a,x:(r7+$28)
        move    x:(r6+$5),a
        cmp     x0,a
        bne     sv_mix_target
        move    #>$7fffff,a
sv_mix_target:
        move    a,x:(r7+$29)
; Start at loaded values only on first clean call, with an empty tank.
        move    x:(r7+$3e),a
        tst     a
        beq     sv_run
        move    r7,r4
        move    #>$24,n4
        move    (r4)+n4
        move    r7,r5
        move    #>$2a,n5
        move    (r5)+n5
        do      #6,>sv_start_values
        move    x:(r4)+,a
        move    a,x:(r5)+
sv_start_values:
        nop
        clr     a
        move    a,x:(r7+$3e)
; Clearing passed dry audio, so fade in the loaded MIX from the same dry gain.
        move    a,x:(r7+$2f)
sv_run:
        move    #>$3fff,m4
        move    #>$3fff,m5
        move    x:(r7+$21),r5
        move    #>$1,n0
        do      n7,>sv_end
        move    x:(r7+$24),a
        move    x:(r7+$2a),b
        sub     b,a
        asr     #$8,a,a
        move    a,x0
        move    x0,a
        tst     a
        move    x:(r7+$24),x1
        teq     x1,b
        add     b,a
        move    a,x:(r7+$2a)
        move    x:(r7+$26),a
        move    x:(r7+$2c),b
        sub     b,a
        asr     #$8,a,a
        move    a,x0
        move    x0,a
        tst     a
        move    x:(r7+$26),x1
        teq     x1,b
        add     b,a
        move    a,x:(r7+$2c)
        move    x:(r7+$27),a
        move    x:(r7+$2d),b
        sub     b,a
        asr     #$8,a,a
        move    a,x0
        move    x0,a
        tst     a
        move    x:(r7+$27),x1
        teq     x1,b
        add     b,a
        move    a,x:(r7+$2d)
        move    x:(r7+$28),a
        move    x:(r7+$2e),b
        sub     b,a
        asr     #$8,a,a
        move    a,x0
        move    x0,a
        tst     a
        move    x:(r7+$28),x1
        teq     x1,b
        add     b,a
        move    a,x:(r7+$2e)
        move    x:(r7+$29),a
        move    x:(r7+$2f),b
        sub     b,a
        asr     #$8,a,a
        move    a,x0
        move    x0,a
        tst     a
        move    x:(r7+$29),x1
        teq     x1,b
        add     b,a
        move    a,x:(r7+$2f)
; Slow SIZE glide carries discarded fraction, avoiding a final tap jump.
        move    x:(r7+$25),a
        move    x:(r7+$2b),b
        sub     b,a
        move    x:(r7+$1f),x0
        add     x0,a
        move    a,x1
        and     #>$7ff,a
        move    a1,x0
        move    x0,x:(r7+$1f)
        move    x1,a
        asr     #$b,a,a
        add     b,a
        move    a,x:(r7+$2b)
        move    x:(r7+$2e),x0
        move    #>$333333,y1
        mpy     x0,y1,a
        add     #>$3d70a4,a
        move    a,x:(r7+$1e)
        move    x:(r0),a
        asr     #$3,a,a
        move    a,x1
        move    x:(r7+$18),b
        sub     b,a
        move    x:(r7+$3f),x0
        add     x0,a
        tfr     a,b
        and     #>$3ff,b
        move    b1,x0
        move    x0,x:(r7+$3f)
        asr     #$a,a,a
        move    x:(r7+$18),b
        add     b,a
        move    a,x:(r7+$18)
        move    x1,b
        sub     a,b
        move    b,x:(r7+$30)
        move    x:(r0+n0),a
        asr     #$3,a,a
        move    a,x1
        move    x:(r7+$19),b
        sub     b,a
        move    x:(r7+$40),x0
        add     x0,a
        tfr     a,b
        and     #>$3ff,b
        move    b1,x0
        move    x0,x:(r7+$40)
        asr     #$a,a,a
        move    x:(r7+$19),b
        add     b,a
        move    a,x:(r7+$19)
        move    x1,b
        sub     a,b
        move    b,x:(r7+$31)
        move    x:(r7+$30),a
        move    #>$ffff8f,n5
        move    y:(r5+n5),b
        move    b,x0
        move    #>$500000,y1
        mac     -x0,y1,a
        move    #>$000000,n5
        move    a,y:(r5+n5)
        move    a,x0
        move    b,a
        mac     x0,y1,a
        move    #>$fffe07,n5
        move    y:(r5+n5),b
        move    b,x0
        move    #>$500000,y1
        mac     -x0,y1,a
        move    #>$fffee0,n5
        move    a,y:(r5+n5)
        move    a,x0
        move    b,a
        mac     x0,y1,a
        move    a,x:(r7+$32)
        move    x:(r7+$31),a
        move    #>$fffee1,n5
        move    y:(r5+n5),b
        move    b,x0
        move    #>$500000,y1
        mac     -x0,y1,a
        move    #>$ffff8e,n5
        move    a,y:(r5+n5)
        move    a,x0
        move    b,a
        mac     x0,y1,a
        move    #>$fffcd3,n5
        move    y:(r5+n5),b
        move    b,x0
        move    #>$500000,y1
        mac     -x0,y1,a
        move    #>$fffe06,n5
        move    a,y:(r5+n5)
        move    a,x0
        move    b,a
        mac     x0,y1,a
        move    a,x:(r7+$33)
; Branch1: interpolated SIZE delay, damping and fixed diffuser.
        move    x:(r7+$2b),x0
        move    #>$5bf000,y1
        mpy     x0,y1,a
        move    a,x1
        asr     #$c,a,a
        move    a1,y0
        move    x1,a
        and     #>$fff,a
        asl     #$b,a,a
        move    a,y1
        move    #>$fffcd2,a
        sub     y0,a
        move    a,n5
        lua     (r5+n5),r4
        move    y:(r4)-,b
        move    y:(r4),a
        sub     b,a
        move    a,x0
        mpy     x0,y1,a
        add     b,a
        move    x:(r7+$10),b
        sub     b,a
        move    a,x0
        move    x:(r7+$1e),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$10)
        move    #>$fff5fc,n5
        move    y:(r5+n5),b
        move    b,x0
        move    #>$400000,y1
        mac     -x0,y1,a
        move    #>$fff711,n5
        move    a,y:(r5+n5)
        move    a,x0
        move    b,a
        mac     x0,y1,a
        move    a,x:(r7+$34)
; Branch2: interpolated SIZE delay, damping and fixed diffuser.
        move    x:(r7+$2b),x0
        move    #>$641000,y1
        mpy     x0,y1,a
        move    a,x1
        asr     #$c,a,a
        move    a1,y0
        move    x1,a
        and     #>$fff,a
        asl     #$b,a,a
        move    a,y1
        move    #>$fff5fb,a
        sub     y0,a
        move    a,n5
        lua     (r5+n5),r4
        move    y:(r4)-,b
        move    y:(r4),a
        sub     b,a
        move    a,x0
        mpy     x0,y1,a
        add     b,a
        move    x:(r7+$11),b
        sub     b,a
        move    a,x0
        move    x:(r7+$1e),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$11)
        move    #>$ffee12,n5
        move    y:(r5+n5),b
        move    b,x0
        move    #>$400000,y1
        mac     -x0,y1,a
        move    #>$ffefb7,n5
        move    a,y:(r5+n5)
        move    a,x0
        move    b,a
        mac     x0,y1,a
        move    a,x:(r7+$35)
; Branch3: interpolated SIZE delay, damping and fixed diffuser.
        move    x:(r7+$2b),x0
        move    #>$6f1000,y1
        mpy     x0,y1,a
        move    a,x1
        asr     #$c,a,a
        move    a1,y0
        move    x1,a
        and     #>$fff,a
        asl     #$b,a,a
        move    a,y1
        move    #>$ffee11,a
        sub     y0,a
        move    a,n5
        lua     (r5+n5),r4
        move    y:(r4)-,b
        move    y:(r4),a
        sub     b,a
        move    a,x0
        mpy     x0,y1,a
        add     b,a
        move    x:(r7+$12),b
        sub     b,a
        move    a,x0
        move    x:(r7+$1e),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$12)
        move    #>$ffe4fa,n5
        move    y:(r5+n5),b
        move    b,x0
        move    #>$400000,y1
        mac     -x0,y1,a
        move    #>$ffe71d,n5
        move    a,y:(r5+n5)
        move    a,x0
        move    b,a
        mac     x0,y1,a
        move    a,x:(r7+$36)
; Branch4: interpolated SIZE delay, damping and fixed diffuser.
        move    x:(r7+$2b),x0
        move    #>$7cf000,y1
        mpy     x0,y1,a
        move    a,x1
        asr     #$c,a,a
        move    a1,y0
        move    x1,a
        and     #>$fff,a
        asl     #$b,a,a
        move    a,y1
        move    #>$ffe4f9,a
        sub     y0,a
        move    a,n5
        lua     (r5+n5),r4
        move    y:(r4)-,b
        move    y:(r4),a
        sub     b,a
        move    a,x0
        mpy     x0,y1,a
        add     b,a
        move    x:(r7+$13),b
        sub     b,a
        move    a,x0
        move    x:(r7+$1e),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$13)
        move    #>$ffda7c,n5
        move    y:(r5+n5),b
        move    b,x0
        move    #>$400000,y1
        mac     -x0,y1,a
        move    #>$ffdd27,n5
        move    a,y:(r5+n5)
        move    a,x0
        move    b,a
        mac     x0,y1,a
        move    a,x:(r7+$37)
        move    x:(r7+$34),a
        move    x:(r7+$36),x0
        sub     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$38)
        move    x:(r7+$35),a
        move    x:(r7+$37),x0
        sub     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$39)
; L original8-poleButterworth4500Hz, before any upward resampling.
        move    x:(r7+$38),a
        move    a,x1
        move    #>$0802ad,y0
        mpy     x1,y0,a
        move    x:(r7+$0),x0
        add     x0,a
        move    a,y1
        mpy     x1,y0,b
        asl     #$1,b,b
        move    #>$40a762,x0
        mac     x0,y1,b
        mac     x0,y1,b
        move    x:(r7+$1),x0
        add     x0,b
        move    b,x:(r7+$0)
        mpy     x1,y0,b
        move    #>$215978,x0
        mac     -x0,y1,b
        move    b,x:(r7+$1)
        move    y1,a
        move    a,x1
        move    #>$087cfd,y0
        mpy     x1,y0,a
        move    x:(r7+$2),x0
        add     x0,a
        move    a,y1
        mpy     x1,y0,b
        asl     #$1,b,b
        move    #>$448297,x0
        mac     x0,y1,b
        mac     x0,y1,b
        move    x:(r7+$3),x0
        add     x0,b
        move    b,x:(r7+$2)
        mpy     x1,y0,b
        move    #>$2af923,x0
        mac     -x0,y1,b
        move    b,x:(r7+$3)
        move    y1,a
        move    a,x1
        move    #>$098a23,y0
        mpy     x1,y0,a
        move    x:(r7+$4),x0
        add     x0,a
        move    a,y1
        mpy     x1,y0,b
        asl     #$1,b,b
        move    #>$4cfeee,x0
        mac     x0,y1,b
        mac     x0,y1,b
        move    x:(r7+$5),x0
        add     x0,b
        move    b,x:(r7+$4)
        mpy     x1,y0,b
        move    #>$402667,x0
        mac     -x0,y1,b
        move    b,x:(r7+$5)
        move    y1,a
        move    a,x1
        move    #>$0b61a8,y0
        mpy     x1,y0,a
        move    x:(r7+$6),x0
        add     x0,a
        move    a,y1
        mpy     x1,y0,b
        asl     #$1,b,b
        move    #>$5bdcaa,x0
        mac     x0,y1,b
        mac     x0,y1,b
        move    x:(r7+$7),x0
        add     x0,b
        move    b,x:(r7+$6)
        mpy     x1,y0,b
        move    #>$653ff6,x0
        mac     -x0,y1,b
        move    b,x:(r7+$7)
        move    y1,a
        move    #>$ffda7b,n5
        move    a,y:(r5+n5)
; Continuous phase: PTCH moves speed, never jumps or resets a read head.
        move    x:(r7+$2c),a
        asr     #$8,a,a
        move    x:(r7+$3c),x0
        add     x0,a
        and     #>$7fffff,a
        move    a1,x0
        move    x0,x:(r7+$3c)
; Smooth complementary window, normalized by head2+w*(head1-head2).
        move    x0,a
        sub     #>$400000,a
        abs     a
        asl     #$1,a,a
        move    #>$7fffff,b
        sub     a,b
        move    #>$0,x1
        tst     b
        tmi     x1,b
; C1 crossfade w*w*(3-2*w): zero slope at grain births and seams.
; Keep products wide until subtraction; no intermediate above1 is stored.
        move    b,x1
        move    x1,y0
        mpy     x1,y0,a
        move    a,y0
        mpy     x1,y0,b
        asl     #$1,b,b
        move    y0,a
        add     y0,a
        add     y0,a
        sub     b,a
        move    a,x:(r7+$1d)
        move    x0,a
        move    #>$ffda79,y0
        bsr     sv_tap
        move    a,x:(r7+$1c)
        move    x:(r7+$3c),a
        add     #>$400000,a
        and     #>$7fffff,a
        move    a1,x0
        move    x0,a
        move    #>$ffda79,y0
        bsr     sv_tap
        move    a,b
        move    x:(r7+$1c),a
        sub     b,a
        move    a,x0
        move    x:(r7+$1d),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$30)
; R original8-poleButterworth4500Hz, before any upward resampling.
        move    x:(r7+$39),a
        move    a,x1
        move    #>$0802ad,y0
        mpy     x1,y0,a
        move    x:(r7+$8),x0
        add     x0,a
        move    a,y1
        mpy     x1,y0,b
        asl     #$1,b,b
        move    #>$40a762,x0
        mac     x0,y1,b
        mac     x0,y1,b
        move    x:(r7+$9),x0
        add     x0,b
        move    b,x:(r7+$8)
        mpy     x1,y0,b
        move    #>$215978,x0
        mac     -x0,y1,b
        move    b,x:(r7+$9)
        move    y1,a
        move    a,x1
        move    #>$087cfd,y0
        mpy     x1,y0,a
        move    x:(r7+$a),x0
        add     x0,a
        move    a,y1
        mpy     x1,y0,b
        asl     #$1,b,b
        move    #>$448297,x0
        mac     x0,y1,b
        mac     x0,y1,b
        move    x:(r7+$b),x0
        add     x0,b
        move    b,x:(r7+$a)
        mpy     x1,y0,b
        move    #>$2af923,x0
        mac     -x0,y1,b
        move    b,x:(r7+$b)
        move    y1,a
        move    a,x1
        move    #>$098a23,y0
        mpy     x1,y0,a
        move    x:(r7+$c),x0
        add     x0,a
        move    a,y1
        mpy     x1,y0,b
        asl     #$1,b,b
        move    #>$4cfeee,x0
        mac     x0,y1,b
        mac     x0,y1,b
        move    x:(r7+$d),x0
        add     x0,b
        move    b,x:(r7+$c)
        mpy     x1,y0,b
        move    #>$402667,x0
        mac     -x0,y1,b
        move    b,x:(r7+$d)
        move    y1,a
        move    a,x1
        move    #>$0b61a8,y0
        mpy     x1,y0,a
        move    x:(r7+$e),x0
        add     x0,a
        move    a,y1
        mpy     x1,y0,b
        asl     #$1,b,b
        move    #>$5bdcaa,x0
        mac     x0,y1,b
        mac     x0,y1,b
        move    x:(r7+$f),x0
        add     x0,b
        move    b,x:(r7+$e)
        mpy     x1,y0,b
        move    #>$653ff6,x0
        mac     -x0,y1,b
        move    b,x:(r7+$f)
        move    y1,a
        move    #>$ffd277,n5
        move    a,y:(r5+n5)
; Continuous phase: PTCH moves speed, never jumps or resets a read head.
        move    x:(r7+$2c),a
        asr     #$8,a,a
        move    x:(r7+$3d),x0
        add     x0,a
        and     #>$7fffff,a
        move    a1,x0
        move    x0,x:(r7+$3d)
; Smooth complementary window, normalized by head2+w*(head1-head2).
        move    x0,a
        sub     #>$400000,a
        abs     a
        asl     #$1,a,a
        move    #>$7fffff,b
        sub     a,b
        move    #>$0,x1
        tst     b
        tmi     x1,b
; C1 crossfade w*w*(3-2*w): zero slope at grain births and seams.
; Keep products wide until subtraction; no intermediate above1 is stored.
        move    b,x1
        move    x1,y0
        mpy     x1,y0,a
        move    a,y0
        mpy     x1,y0,b
        asl     #$1,b,b
        move    y0,a
        add     y0,a
        add     y0,a
        sub     b,a
        move    a,x:(r7+$1d)
        move    x0,a
        move    #>$ffd275,y0
        bsr     sv_tap
        move    a,x:(r7+$1c)
        move    x:(r7+$3d),a
        add     #>$400000,a
        and     #>$7fffff,a
        move    a1,x0
        move    x0,a
        move    #>$ffd275,y0
        bsr     sv_tap
        move    a,b
        move    x:(r7+$1c),a
        sub     b,a
        move    a,x0
        move    x:(r7+$1d),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$31)
        move    x:(r7+$30),a
        move    x:(r7+$34),b
        sub     b,a
        move    a,x0
        move    x:(r7+$2d),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$34)
        move    x:(r7+$31),a
        move    x:(r7+$35),b
        sub     b,a
        move    a,x0
        move    x:(r7+$2d),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$35)
        move    x:(r7+$30),a
        neg     a
        move    x:(r7+$36),b
        sub     b,a
        move    a,x0
        move    x:(r7+$2d),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$36)
        move    x:(r7+$31),a
        neg     a
        move    x:(r7+$37),b
        sub     b,a
        move    a,x0
        move    x:(r7+$2d),y1
        mpy     x0,y1,a
        add     b,a
        move    a,x:(r7+$37)
; Householder uses mean in24bits and reconstructs half-sum only wide.
        move    x:(r7+$34),a
        move    x:(r7+$35),x0
        add     x0,a
        move    x:(r7+$36),x0
        add     x0,a
        move    x:(r7+$37),x0
        add     x0,a
        asr     #$2,a,a
        move    a,x:(r7+$3a)
        move    a,x0
        move    x:(r7+$2a),y1
        mpy     x0,y1,a
        move    a,x:(r7+$3b)
        move    x:(r7+$3b),a
        asl     #$1,a,a
        move    x:(r7+$34),x0
        mac     -x0,y1,a
        move    x:(r7+$32),x0
        add     x0,a
        move    #>$fffcd2,n5
        move    a,y:(r5+n5)
        move    x:(r7+$3b),a
        asl     #$1,a,a
        move    x:(r7+$35),x0
        mac     -x0,y1,a
        move    x:(r7+$33),x0
        add     x0,a
        move    #>$fff5fb,n5
        move    a,y:(r5+n5)
        move    x:(r7+$3b),a
        asl     #$1,a,a
        move    x:(r7+$36),x0
        mac     -x0,y1,a
        move    x:(r7+$32),x0
        sub     x0,a
        move    #>$ffee11,n5
        move    a,y:(r5+n5)
        move    x:(r7+$3b),a
        asl     #$1,a,a
        move    x:(r7+$37),x0
        mac     -x0,y1,a
        move    x:(r7+$33),x0
        sub     x0,a
        move    #>$ffe4f9,n5
        move    a,y:(r5+n5)
        move    x:(r7+$38),a
        asl     #$1,a,a
        move    a,x1
        move    x:(r7+$16),b
        sub     b,a
        asr     #$4,a,a
        add     b,a
        move    a,x:(r7+$16)
        move    x:(r7+$2e),b
        tst     b
        bge     sv_left_band
        sub     x1,a
sv_left_band:
        move    a,x0
        move    b,y1
        mpy     x0,y1,a
        move    x1,b
        sub     a,b
        move    b,x1
        move    x:(r7+$1a),a
        sub     a,b
        move    x:(r7+$41),x0
        add     x0,b
        tfr     b,a
        and     #>$3ff,a
        move    a1,x0
        move    x0,x:(r7+$41)
        asr     #$a,b,b
        move    x:(r7+$1a),a
        add     b,a
        move    a,x:(r7+$1a)
        move    x1,b
        sub     a,b
; Weighted products avoid overflowing a full-scale wet-dry difference.
        move    b,x0
        move    x:(r7+$2f),y1
        mpy     x0,y1,a
        move    #>$7fffff,b
        sub     y1,b
        move    b,y1
        move    x:(r0),x0
        mac     x0,y1,a
        move    x:(r7+$2f),b
        tst     b
        teq     x0,a
        move    a,x:(r0)+
        move    x:(r7+$39),a
        asl     #$1,a,a
        move    a,x1
        move    x:(r7+$17),b
        sub     b,a
        asr     #$4,a,a
        add     b,a
        move    a,x:(r7+$17)
        move    x:(r7+$2e),b
        tst     b
        bge     sv_right_band
        sub     x1,a
sv_right_band:
        move    a,x0
        move    b,y1
        mpy     x0,y1,a
        move    x1,b
        sub     a,b
        move    b,x1
        move    x:(r7+$1b),a
        sub     a,b
        move    x:(r7+$42),x0
        add     x0,b
        tfr     b,a
        and     #>$3ff,a
        move    a1,x0
        move    x0,x:(r7+$42)
        asr     #$a,b,b
        move    x:(r7+$1b),a
        add     b,a
        move    a,x:(r7+$1b)
        move    x1,b
        sub     a,b
; Weighted products avoid overflowing a full-scale wet-dry difference.
        move    b,x0
        move    x:(r7+$2f),y1
        mpy     x0,y1,a
        move    #>$7fffff,b
        sub     y1,b
        move    b,y1
        move    x:(r0),x0
        mac     x0,y1,a
        move    x:(r7+$2f),b
        tst     b
        teq     x0,a
        move    a,x:(r0)+
        move    (r5)+
sv_end:
        nop
        move    r5,x:(r7+$21)
        move    #>$ffffff,m4
        move    #>$ffffff,m5
        rts
; Q11.12 lag in a, integer write offset in y0. The two neighbors remain
; inside the reserved segment. Straight-line helper priced at every call.
sv_tap:
        move    a,x0
        asr     #$c,a,a
        move    a1,x1
        move    x0,a
        and     #>$fff,a
        asl     #$b,a,a
        move    a,y1
        move    y0,a
        sub     x1,a
        move    a,n5
        lua     (r5+n5),r4
        move    y:(r4)-,b
        move    y:(r4),a
        sub     b,a
        move    a,x0
        mpy     x0,y1,a
        add     b,a
        rts
